<?php
/**
 * @file
 * Code for the OS2web - Borger.dk feature.
 */

include_once 'os2web_borger_dk.features.inc';

/**
 * Implements hook_menu().
 */
function os2web_borger_dk_menu() {
  $items = array();
  $items['admin/config/os2web_borger_dk'] = array(
    'title' => 'O2web borger.dk settings',
    'description' => 'General settings for Borger.dk articles, fx, modify fields display, editable and syncronization time',
    'position' => 'right',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/config/os2web_borger_dk/settings'] = array(
    'title' => 'OS2web Borger.dk Settings',
    'description' => 'General settings for the OS2Web borger.dk',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2web_borger_dk_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'os2web_borger_dk.admin.inc',
  );

  $items['admin/borgerdk/debug'] = array(
    'title' => 'OS2web Borger.dk Debug',
    'description' => 'Debug OS2Web Borger.dk Articles',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('os2web_borger_dk_articles_debug_form'),
    'access arguments' => array('administer site configuration'),
  );

  $items['import/os2web_borger_dk/autocomplete'] = array(
    'page callback' => '_os2web_borger_dk_autocomplete_callback',
    'page arguments' => array(3),
    'access arguments' => array('create os2web_borger_dk_article content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function os2web_borger_dk_articles_debug_form($form, $form_state) {
  $form['delete_menu'] = array(
    '#type'   => 'submit',
    '#value'  => 'Debug Cron Borger.dk-Menu now',
    '#submit' => array('os2web_borger_dk_debug_form_submit')
  );
  $form['delete_form'] = array(
    '#type'   => 'submit',
    '#value'  => 'Debug Cron FORM-taxonomies now',
    '#submit' => array('os2web_borger_dk_debug_form_submit')
  );

  return $form;
}

/**
 * Function _os2web_borger_dk_autocomplete_callback().
 */
function _os2web_borger_dk_autocomplete_callback($string = '') {
  $matches = array();

  if ($string) {
    $result = db_query("SELECT `ArticleID`, `ArticleStatus`, `ArticleTitle` FROM {os2web_borger_dk_article_titles} WHERE `ArticleStatus` >= 0 AND LOWER(ArticleTitle) LIKE LOWER('" . $string . "%') LIMIT 10");
    // Add matches to $matches.
    foreach ($result as $row) {
      if ($row->ArticleStatus > 0) {
        $row_name = $row->ArticleTitle . ' [*](ID:' . $row->ArticleID . ')';
      }
      else {
        $row_name = $row->ArticleTitle . ' (ID:' . $row->ArticleID . ')';
      }
      $matches[$row_name] = check_plain($row_name);
    }
  }
  drupal_json_output($matches);
}

/**
 * Implements hook_form_alter().
 */
function os2web_borger_dk_form_alter(&$form, &$form_state, $form_id) {
  static $os2web_borger_dk_falter_form;
  if (isset($form['type']) && isset($form['#node'])) {
    if ($form_id == 'os2web_borger_dk_article_node_form') {

      if (isset($os2web_borger_dk_falter_form) && !empty($os2web_borger_dk_falter_form)) {
        // If the static form-cache has already been build then
        // we simply return the form-cache value instead of
        // building the whole form twice per request.
        $form = $os2web_borger_dk_falter_form;
      }
      else {
        $node = $form_state['node'];
        $titles_autocomplete = variable_get('os2web_borger_dk_titles_sync', FALSE);
        if (!isset($node->nid) || isset($node->is_new)) {
          os2web_borger_dk_autocomplete_form($form, $form_state);
        }

        //$locked_os2web_types = array('field_os2web_borger_dk_borgerurl' => 1, 'field_os2web_borger_dk_formterm' => 2, 'field_termref_kle' => 2);
        $locked_os2web_types = array('field_os2web_borger_dk_borgerurl' => 1);
        $admin_display_fields = variable_get('os2web_borger_dk_display');

        $data = field_info_instances('node', 'os2web_borger_dk_article');
        // First we create a list of all field-names and labels.
        $checkbox_opts = array();
        $initial_values = array();

        $data['title'] = array('label' => 'Title');
        $visible_items = (isset($form['#node']->os2web_borger_dk_article['field_settings'])) ? $form['#node']->os2web_borger_dk_article['field_settings'] : NULL;
        $admin_last_settings = variable_get('os2web_borger_dk_admin_last_settings');

        foreach ($data as $type => $item) {
          // Then we insert field label to our checkboxes options.
          $checkbox_opts[$type] = t($item['label']);

          // admin-config says we should show this item as an option.
          if ($admin_display_fields[$type]) {
            if (empty($visible_items) || (!empty($visible_items) && !empty($visible_items[$type]))) {
              // If visible_items is empty that means we should use admin-config
              // or if the type of visible_items is set, and set to be displayed
              // then we add this type to the default_values.
              $initial_values[] = $type;
            }
            else {
              if ($admin_last_settings[$type] != $admin_display_fields[$type] && $visible_items[$type] == $admin_last_settings[$type]) {
                $initial_values[] = $type;
              }
            }
          }
        }
        variable_set('os2web_borger_dk_admin_last_settings', $admin_display_fields);

        // This is the field fieldset.
        $form['fields_visible_formset'] = array(
          '#type' => 'fieldset',
          '#title' => t('Toggle display'),
          '#collapsible' => TRUE,
          '#description' => t('Set the visibility of article fields.'),
          '#group' => 'additional_settings',
        );
        $form['fields_visible_formset']['os2web_borger_dk_field_settings'] = array(
          '#type' => 'checkboxes',
          '#options' => $checkbox_opts,
          '#description' => t("Check or uncheck the respective fields"),
          '#default_value' => $initial_values,
          '#after_build' => array('os2web_borger_dk_process_checkboxes_os2web_borger_dk_article'),
          '#group' => 'additional_settings',
        );

        if (isset($form['#node']->nid)) {
          $form['actions']['os2web_borger_dk_synchronize'] = array(
            '#type' => 'submit',
            '#value' => t("Update article now"),
            '#weight' => 100,
            '#access' => variable_get('node_preview_' . $node->type, DRUPAL_OPTIONAL) != DRUPAL_REQUIRED || (!form_get_errors() && isset($form_state['node_preview'])),
            '#submit' => array('os2web_borger_dk_sync_submit'),
          );
        }
        $form['#after_build'][] = 'os2web_borger_dk_after_build';

        // Micro articles.
        if (isset($form['#node']->nid)) {
          $microarticle = variable_get('os2web_borger_dk_microarticle_active');
          $value_editable = variable_get('os2web_borger_dk_editable', array(NULL));
          // If microarticle is set up to show.
          if ($microarticle) {
            $field_microarticle_settings = (isset($form['#node']->os2web_borger_dk_microarticle['field_microarticle_settings'])) ? $form['#node']->os2web_borger_dk_microarticle['field_microarticle_settings'] : NULL;
            $body_text = (isset($form['body']['und']['0']['#entity']->body['und']['0']['value'])) ? $form['body']['und']['0']['#entity']->body['und']['0']['value'] : '';
            unset($form['body']);

            // Link break: in windows \r\n, linux \n.
            preg_match("/<\/div>\n/", $body_text, $link_break);
            if (isset($link_break[0])) {
              $div = preg_split("/\n<\/div>\n/", $body_text, -1, PREG_SPLIT_DELIM_CAPTURE);
            }
            else {
              $div = preg_split('/\r\n<[\/]div>\r\n/', $body_text, -1, PREG_SPLIT_DELIM_CAPTURE);
            }

            foreach ($div as $key => $text) {
              $microno = $key + 1;
              $checkboxno = 'os2web_borger_dk_micro_' . $microno;
              $h2_text_field = 'os2web_borger_dk_micro_h2_' . $microno;
              $text_area = 'os2web_borger_dk_micro_textarea_' . $microno;

              // The last div is a link break.
              if ($key != count($div) - 1) {
                // Frist we get the microarticle title.
                preg_match("/<h2 class=\"mArticle\" id=\"mArticle" . $microno . "\">(.*?)<\/h2>/", $div[$key], $match);
                $h2 = isset($match[1]) ? $match[1] : '';

                // Then we get the div content.
                preg_match("/<div class=\"mArticle" . $microno . " mArticle\">(.*?)\r\n    <\/div>/s", $div[$key], $match2);
                $micro_text = isset($match2[1]) ? $match2[1] : '';

                // For each microarticle we build a fieldset, a textfield for
                // title, a textarea for div content and a checkbox for
                // visibility option.
                $form['os2web_borger_dk_micro_settings_' . $microno] = array(
                  '#type' => 'fieldset',
                );

                $form['os2web_borger_dk_micro_settings_' . $microno][$h2_text_field] = array(
                  '#type' => 'textfield',
                  '#title' => t(' Title of Microarticle ') . $microno,
                  '#default_value' => variable_get($h2_text_field, $h2),
                );
                // If body (article text) visible/editable option is checked
                // by ADMIN and EDITOR, then forms disabled is false.
                if ($visible_items['body'] === "body" && $admin_display_fields['body'] === "body" && $value_editable['body'] === "body") {
                  $form['os2web_borger_dk_micro_settings_' . $microno][$text_area] = array(
                    // '#title' => t('Microarticle ' . $microno),
                    '#type' => 'textarea',
                    '#default_value' => $micro_text,
                  );

                  $form['os2web_borger_dk_micro_settings_' . $microno][$checkboxno] = array(
                    '#type' => 'checkbox',
                    '#title' => t('Visible'),
                    '#description' => t("Check to display this microarticle"),
                    '#default_value' => isset($field_microarticle_settings[$microno]) ? $field_microarticle_settings[$microno] : 1,
                  );
                }
                // If body (article text) display option is UNCHECKED
                // by ADMIN or EDITOR, then forms disabled is TRUE.
                else {
                  $form['os2web_borger_dk_micro_settings_' . $microno][$text_area] = array(
                    '#title' => t('Microarticle ') . $microno,
                    '#type' => 'textarea',
                    '#disabled' => TRUE,
                    '#default_value' => $micro_text,
                    '#description' => t("Please check 'Article text' visible option below in 'Toggle display', or in OS2web borger.dk Settings (Toggle display/Editable article fields) to show/edit this microarticle."),
                  );
                  // If this microarticle is NOT editable.
                  if ($value_editable['body'] !== "body") {
                    $form['os2web_borger_dk_micro_settings_' . $microno][$checkboxno] = array(
                      '#type' => 'checkbox',
                      '#title' => t('Microarticle Visibility'),
                      '#description' => t("Check to display this microarticle"),
                      '#default_value' => isset($field_microarticle_settings[$microno]) ? $field_microarticle_settings[$microno] : 1,
                    );
                  }
                  else {
                    $form['os2web_borger_dk_micro_settings_' . $microno][$checkboxno] = array(
                      '#type' => 'checkbox',
                      '#title' => t('Microarticle Visibility'),
                      '#disabled' => TRUE,
                      '#description' => t("Check to display this microarticle"),
                      '#default_value' => isset($field_microarticle_settings[$microno]) ? $field_microarticle_settings[$microno] : 1,
                    );
                  }
                }
              }
            }
          }
        }

        if (isset($form['#node']->nid) && ($microarticle)) {
          $form['actions']['os2web_borger_dk_microarticles_update'] = array(
            '#type' => 'submit',
            '#value' => t("Update microarticle content"),
            '#weight' => 101,
            '#access' => variable_get('node_preview_' . $node->type, DRUPAL_OPTIONAL) != DRUPAL_REQUIRED || (!form_get_errors() && isset($form_state['node_preview'])),
            '#submit' => array('os2web_borger_dk_microarticles_update_submit'),
          );
        }
        // End of microarticles.
        // Before we exit this function we set the static form-cache value
        // so that later calls to this function handling the same request
        // can return much faster (instead of building the same form twice).
        $os2web_borger_dk_falter_form = $form;
      }
    }
  }
}

/**
 * Function os2web_borger_dk_autocomplete_form().
 */
function os2web_borger_dk_autocomplete_form(&$form, $form_state) {
  $titles_autocomplete = variable_get('os2web_borger_dk_titles_sync', FALSE);
  $title_search_state = (isset($form_state['values']['os2web_borger_dk_article_search_method'])) ? TRUE : FALSE;
  $url_search = !$title_search_state;

  $form['os2web_borger_dk_article_import'] = array(
    '#type' => 'fieldset',
    '#title' => t('Import Borger.dk Article'),
    '#collapsible' => FALSE,
  );

  $form['os2web_borger_dk_article_import']['os2web_borger_dk_article_url_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Borger.dk Article URL'),
    '#default_value' => (isset($form_state['values']['os2web_borger_dk_article_url_text'])) ? $form_state['values']['os2web_borger_dk_article_url_text'] : '',
    '#size' => 60,
    '#maxlength' => 255,
  );

  if ($titles_autocomplete) {
    $form['os2web_borger_dk_article_import']['os2web_borger_dk_article_title_text'] = array(
      '#type' => 'textfield',
      '#title' => t('Borger.dk Article title'),
      '#default_value' => (isset($form_state['values']['os2web_borger_dk_article_title_text'])) ? $form_state['values']['os2web_borger_dk_article_title_text'] : '',
      '#autocomplete_path' => 'import/os2web_borger_dk/autocomplete',
      '#size' => 60,
      '#maxlength' => 255,
      '#attributes' => array('class' => array('auto_submit')),
    );

    $form['os2web_borger_dk_article_import']['os2web_borger_dk_article_title_search'] = array(
      '#type' => 'checkbox',
      '#title' => t('Search for Borger.dk Article by Title-search'),
      '#description' => t('If checked Borger.dk articles are found by title (by URL if un-checked).'),
      '#default_value' => ($url_search) ? 1 : 0,
      '#after_build' => array('_os2web_borger_dk_autocomplete_form_load_js'),
    );
  }
}

/**
 * Function _os2web_borger_dk_autocomplete_form_load_js().
 */
function _os2web_borger_dk_autocomplete_form_load_js($element) {
  $autosubmit_js = '
    $(document).ready(function(){
      Drupal.jsAC.prototype.select = function (node) {
        this.input.value = $(node).data("autocompleteValue");
        if(jQuery(this.input).hasClass("auto_submit")){
          this.input.form.submit();
        }
      };
    });';
  $must_auto_submit = variable_get('os2web_borger_dk_titles_search_auto_submit', FALSE);
  if (!$must_auto_submit) {
    $autosubmit_js = '';
  }
  $js = '(function ($) {
    Drupal.behaviors.switchfield = {
      attach: function(context, settings) {
        var checked1 = $("#edit-os2web-borger-dk-article-title-search").attr("checked");
        if (checked1) {
          $(".form-item-os2web-borger-dk-article-url-text").hide();
          $(".form-item-os2web-borger-dk-article-title-text").show();
        }
        else {
          $(".form-item-os2web-borger-dk-article-url-text").show();
          $(".form-item-os2web-borger-dk-article-title-text").hide();
        }

        $("#edit-os2web-borger-dk-article-title-search").click(function() {
          var checked = $(this).attr("checked");
          if (checked) {
            $(".form-item-os2web-borger-dk-article-url-text").hide(500);
            $(".form-item-os2web-borger-dk-article-title-text").show(500);
          }
          else {
            $(".form-item-os2web-borger-dk-article-url-text").show(500);
            $(".form-item-os2web-borger-dk-article-title-text").hide(500);
          }
        });' . $autosubmit_js . '
      }
    }
  })(jQuery);';
  drupal_add_js($js, 'inline');

  return $element;
}

/**
 * Function os2web_borger_dk_after_build().
 */
function os2web_borger_dk_after_build($form, &$form_state) {
  // Some of the fields are handled exclusively by OS2web.
  // These fields are required on node-add, and can NOT be
  // changed later on (ie. locked).
  $locked_os2web_types = array('field_os2web_borger_dk_borgerurl' => 1, 'field_termref_kle' => 2, 'field_os2web_borger_dk_formterm' => 2);
  $nid = $form_state['values']['nid'];
  $admin_display_fields = variable_get('os2web_borger_dk_display', array(NULL));
  $microarticle = variable_get('os2web_borger_dk_microarticle_active');

  // First we check if this is a node/add-type by checking the node->nid.
  if (!empty($nid)) {
    // This is an old node that is being edited.
    // We must unset all form-elements that has been
    // marked as hidden in the admin-display-settings.
    foreach ($admin_display_fields as $type => $item) {
      if (empty($item) && empty($locked_os2web_types[$type])) {
        if (!$microarticle) {
          os2web_borger_dk_fix_disabled($form[$type]);
        }
      }
    }
    // Then we must disable all fields that has been marked as
    // non-editable in the admin-editable-settings.
    $value_editable = variable_get('os2web_borger_dk_editable', array(NULL));
    foreach ($value_editable as $type => $editable) {
      if (empty($editable) || !empty($locked_os2web_types[$type])) {
        if (!$microarticle) {
          os2web_borger_dk_fix_disabled($form[$type]);
        }
      }
      if ($type == 'field_os2web_byline' && !empty($form[$type])) {
        $form[$type]['#format'] = 'plaintext';
      }
    }

    // Finally we lock the special types.
    foreach ($locked_os2web_types as $type => $locked) {
      // If locked = 1 then disable the field.
      if (isset($form[$type]) && $locked == 1) {
        $form[$type]['#required'] = 0;
        $form[$type]['und']['#required'] = 0;
        $form[$type]['und'][0]['#required'] = 0;
        $form[$type]['und'][0]['value']['#required'] = 0;
        os2web_borger_dk_fix_disabled($form[$type]);
      }
    }
  }
  else {
    // This is a brand new node-add form, and we must hide every
    // form-field.
    $data = field_info_instances('node', 'os2web_borger_dk_article');
    foreach ($data as $type => $item) {
      // Some fields must be checked before unsetting or php will
      // die because a string for instance can not be unset.
      if (!isset($locked_os2web_types[$type]) || $locked_os2web_types[$type] == 1) {
        // These fields can safely be unset (so they are hidden).
        unset($form[$type]);
      }
      if (isset($locked_os2web_types[$type]) && $locked_os2web_types[$type] == 2) {
        // These fields must be hidden by unsetting the theme.
        unset($form[$type]['und']['#theme']);
      }
    }
    unset($form['title']);

    if (isset($form['path']['pathauto']['#default_value'])) {
      $form['path']['pathauto']['#checked'] = 0;
    }
    $form['status'] = 0;
    $form['promote'] = 0;
  }

  return $form;
}

/**
 * Function os2web_borger_dk_process_checkboxes_os2web_borger_dk_article().
 */
function os2web_borger_dk_process_checkboxes_os2web_borger_dk_article(&$element) {

  $admin_display_fields = variable_get('os2web_borger_dk_display', array(NULL));
  if (!empty($element)) {
    foreach (element_children($element) as $key) {
      if (!$admin_display_fields[$key]) {
        $element[$key]['#attributes'] = array('disabled' => 'disabled');
        $element[$key]['#description'] = t('Please go to OS2web Borger.dk settings to change the visibility for this field');
      }
    }
  }
  return $element;
}

/**
 * Function os2web_borger_dk_fix_disabled().
 */
function os2web_borger_dk_fix_disabled(&$elements) {
  foreach (element_children($elements) as $key) {
    if (isset($elements[$key]) && $elements[$key]) {
      // Recurse through all child elements.
      os2web_borger_dk_fix_disabled($elements[$key]);
    }
  }
  if (!isset($elements['#attributes'])) {
    $elements['#attributes'] = array();
  }
  $elements['#attributes']['disabled'] = 'disabled';
}

/**
 * Implements hook_node_load().
 */
function os2web_borger_dk_node_load($nodes, $types) {
  // Decide whether any of $types are relevant to our purpose.
  // We only work on the "os2web_borger_dk_article" node-types.
  if (in_array('os2web_borger_dk_article', $types)) {
    // Gather our extra data for each of these nodes.
    $result = db_query('SELECT nid, external_id, external_status, external_url, field_settings, field_microarticle_settings, published_date, last_updated FROM {os2web_borger_dk_article} WHERE nid IN (:nids)', array(':nids' => array_keys($nodes)));
    // Get admin microarticles settings.
    $microarticle = variable_get('os2web_borger_dk_microarticle_active');
    // Add our extra data to the node objects.
    foreach ($result as $record) {
      $field_settings = unserialize($record->field_settings);
      $nodes[$record->nid]->os2web_borger_dk_article = array(
        'external_id'     => $record->external_id,
        'external_status' => $record->external_status,
        'external_url'    => $record->external_url,
        'field_settings'  => $field_settings,
        'published_date'  => $record->published_date,
        'last_updated'    => $record->last_updated,
      );
      // If microarticle option is set to display.
      if ($microarticle) {
        $field_microaritcle_settings = unserialize($record->field_microarticle_settings);
        $nodes[$record->nid]->os2web_borger_dk_microarticle = array(
          'field_microarticle_settings' => $field_microaritcle_settings,
        );
      }
      // If microarticle option is NOT set to display,then we set an empty array
      // to node->os2web_borger_dk_microarticle[''field_microarticle_settings].
      else {
        $nodes[$record->nid]->os2web_borger_dk_microarticle = array(
          'field_microarticle_settings' => '',
        );
      }
    }
  }
}

/**
 * Implements hook_node_view().
 */
function os2web_borger_dk_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'os2web_borger_dk_article') {
    $fields = $node->os2web_borger_dk_article['field_settings'];
    // First get admin display settings.
    $admin_display_fields = variable_get('os2web_borger_dk_display');
    $locked_os2web_types = array('field_os2web_borger_dk_borgerurl' => 1);
    // We get admin microarticle display settings.
    $microarticle = variable_get('os2web_borger_dk_microarticle_active');
    $field_microarticle_settings = $node->os2web_borger_dk_microarticle['field_microarticle_settings'];

    foreach ($admin_display_fields as $type => $value) {
      // If ADMIN set this field to display.
      if ($admin_display_fields[$type]) {
        // Microarticles : if microarticle is set up to show by admin.
        if ($microarticle) {
          $content_field = (isset($node->content[$type]['#field_name']))
          ? $node->content[$type]['#field_name'] : '';
          // Check if content field is body and field_microarticle_settings
          // is NOT empty.
          // The field_microarticle_setting will be empty when a new
          // article is imported and shown in a form, then node_view
          // will display full body text.
          if ($content_field == 'body' && !empty($field_microarticle_settings)) {
            $body_text = $node->body['und']['0']['value'];

            // Link break in body_text: in windows \r\n, linux \n.
            preg_match("/<\/div>\n/", $body_text, $link_break);
            if (isset($link_break[0])) {
              $div = preg_split("/\n<\/div>\n/", $body_text, -1, PREG_SPLIT_DELIM_CAPTURE);
            }
            else {
              $div = preg_split('/\r\n<[\/]div>\r\n/', $body_text, -1, PREG_SPLIT_DELIM_CAPTURE);
            }
            $show_div = '';
            foreach ($div as $key => $text) {
              $microno = $key + 1;
              $checkboxno = 'os2web_borger_dk_micro_' . $microno;
              // The last div is a link break \n or \r\n.
              if ($div[$key] != $div[(count($div) - 1)]) {
                // If editor set this microarticle to be visible,(TRUE)
                if ($field_microarticle_settings[$microno] != 0) {
                  $show_div .= $div[$key];
                  $show_div .= "\n</div>";
                  $show_div .= "\n";
                }
              }
            }
            // Content body shows only visible microarticles/ part of body_text.
            $node->content[$type]['0']['#markup'] = $show_div;
          }
        }
        else {
          $node->content['body']['0']['#markup'] = $node->body['und']['0']['value'];
        }

        // End of microarticles.
        // If EDITOR set this field to be hidden.
        if ($fields[$type] == '0') {
          $content_field = (isset($node->content[$type]['#field_name'])) ? $node->content[$type]['#field_name'] : '';
          if ($content_field == $type) {
            $node->content[$type]['0']['#markup'] = '';
          }
        }
      }

      // If ADMIN set this field to be hidden.
      else {
        $content_field = (isset($node->content[$type]['#field_name'])) ? $node->content[$type]['#field_name'] : '';
        if ($content_field == $type) {
          $node->content[$type]['0']['#markup'] = '';
        }
      }
    }
    drupal_add_js(drupal_get_path('module', 'os2web_borger_dk') . '/js/os2web_borger_dk.js', 'file');
    drupal_add_css(drupal_get_path('module', 'os2web_borger_dk') . '/css/os2web_borger_dk.css', 'file');

    // Set the page-title if field-value is given.
    if (!empty($node->field_os2web_borger_dk_pagetitle['und'][0]['value'])) {
      drupal_set_title($node->field_os2web_borger_dk_pagetitle['und'][0]['value']);
    }
  }
}

/**
 * Implements hook_node_insert().
 */
function os2web_borger_dk_node_insert($node) {
  if ($node->type == 'os2web_borger_dk_article') {
    $borgerdk_data = $node->os2web_borger_dk_article;
    $serialized_data = serialize($borgerdk_data['field_settings']);
    db_insert('os2web_borger_dk_article')
    ->fields(array(
        'nid' => $node->nid,
        'external_id' => $borgerdk_data['external_id'],
        'external_status' => $borgerdk_data['external_status'],
        'external_url' => $borgerdk_data['external_url'],
        'field_settings' => $serialized_data,
        'last_updated' => $borgerdk_data['last_updated'],
        'published_date' => $borgerdk_data['published_date'],
    ))
    ->execute();
  }
}

/**
 * Implements hook_node_delete().
 */
function os2web_borger_dk_node_delete($node) {
  if ($node->type == 'os2web_borger_dk_article') {
    // First we delete the article-data from the node-additions table.
    db_delete('os2web_borger_dk_article')
      ->condition('nid', $node->nid)
      ->execute();
    // Then we set the status to "not imported" in the "Titles list"-table.
    db_update('os2web_borger_dk_article_titles')
      ->fields(array('ArticleStatus' => 0))
      ->condition('ArticleID', $node->os2web_borger_dk_article['external_id'], '=')
      ->execute();
  }
}

/**
 * Implements hook_node_validate().
 */
function os2web_borger_dk_node_validate($node, $form, &$form_state) {
  if ($node->type == 'os2web_borger_dk_article') {
    // Enforce a minimum word length of 3 on punch lines.
    $admin_title_search = variable_get('os2web_borger_dk_titles_sync', FALSE);
    $titles_search = isset($form_state['values']['os2web_borger_dk_article_title_search'])? $form_state['values']['os2web_borger_dk_article_title_search'] : FALSE;
    $url_text = isset($form_state['values']['os2web_borger_dk_article_url_text']) ? $form_state['values']['os2web_borger_dk_article_url_text'] : FALSE;

    // If admin config set up : import Borger.dk article by URL.
    // TODO: Check if this if-statement works as expected, and
    // if we can drop the "!isset($node->nid)" part.
    if ((!$admin_title_search) || ($titles_search == '0' && !isset($node->nid))) {
      if (!$titles_search && !isset($node->nid)) {
        if (!empty($url_text)) {
          $url = $url_text;
          $pos = strpos($url, 'borger.dk/Sider');
          if ($pos === FALSE) {
            form_set_error('os2web_borger_dk_article_url_text', t('The Borger.dk-URL is not valid, please write a valid Borger.dk-URL.'));
          }
        }
        else {
          form_set_error('os2web_borger_dk_article_url_text', t('The Borger.dk-URL is empty, please write a valid Borger.dk-URL.'));
        }
      }
    }
    // If admin config set up : import Borger.dk article by article title.
    else {
      // If search article checkbox by Title-search is CHECKED.
      // TODO: Check if we can drop this if-statement. The else-statement above.
      // should be sufficient if the matched if-statement really works.
      if ($titles_search == '1') {
        $borger_dk_title = !empty($form_state['values']['os2web_borger_dk_article_title_text']) ? $form_state['values']['os2web_borger_dk_article_title_text'] : FALSE;
        if (!$borger_dk_title) {
          form_set_error('os2web_borger_dk_article_title_text', t('The Borger.dk Article title is empty, please write a Borger.dk Article title'));
        }
        $matches = array();
        $aid = 0;
        // This preg_match() looks for the last pattern like
        // [33334] and if found extracts the numeric portion.
        $result = preg_match('/\(ID:([0-9]+)\)$/', $borger_dk_title, $matches);
        if ($result > 0) {
          // If $result is nonzero, we found a match and can use
          // it as the index into $matches.
          $aid = $matches[$result];
          $status = db_query('SELECT ArticleStatus FROM {os2web_borger_dk_article_titles} WHERE ArticleID = :aid', array(':aid' => $aid))->fetchField();
          if ($status < 0) {
            // This article is no longer availlable and we tell the user so.
            drupal_set_message(t('The Borger.dk article with title "!title" is no longer availlable', array('!title' => $borger_dk_url)), 'warning');
            form_set_error('os2web_borger_dk_article_title_text', t('The Borger.dk Article-title has been deleted, please write a valid Borger.dk-URL.'));
          }
        }
      }
    }
  }
}

/**
 * Funtion os2web_borger_dk_sync_submit().
 */
function os2web_borger_dk_sync_submit($form, &$form_state) {
  // Get the node->nid from the form['#node'].
  $nid = $form['#node']->nid;

  // First we find the external_id, and last_update time for this article.
  $data = db_query('SELECT external_id, last_updated FROM {os2web_borger_dk_article} WHERE nid = :nid', array(':nid' => $nid))->fetchObject();

  // Then we fetch the article item from the Borger.dk webservice.
  $wsdl = variable_get('os2web_borger_dk_webservice', 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl');
  $article = _os2web_borger_dk_GetArticleByID($data->external_id, $wsdl);

  $last_update = $data->last_updated;
  $last_article_update = strtotime($article['last_updated']);
  // And we check if the article has been updated before we update the node.
  if ($last_update < $last_article_update) {
    // Now we update the node content with the fetched article content.
    _os2web_borger_dk_update_node_content($nid, $article);
    // And we notify the user that the article has been updated.
    drupal_set_message(t('The article has been updated with new content from Borger.dk'), 'status');
  }
  else {
    // We also notify the user if the article is up to date already.
    drupal_set_message(t('This article is identical to the article from Borger.dk, and has not been updated'), 'status');
  }

  drupal_goto('node/' . $nid . '/edit');
}

/**
 * Function os2web_borger_dk_microarticles_update_submit().
 */
function os2web_borger_dk_microarticles_update_submit($form, &$form_state) {
  // Get the node->nid from the form['#node'].
  $nid = $form['#node']->nid;

  // First we find the external_id, and last_update time for this article.
  $data = db_query('SELECT external_id, last_updated FROM {os2web_borger_dk_article} WHERE nid = :nid', array(':nid' => $nid))->fetchObject();

  // Then we fetch the article item from the Borger.dk webservice.
  $wsdl = variable_get('os2web_borger_dk_webservice', 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl');
  $article = _os2web_borger_dk_GetArticleByID($data->external_id, $wsdl);

  if (empty($article['Exceptions']) && empty($article['error'])) {
    // First we load the corresponding node.
    $node = node_load($nid, NULL, TRUE);
    $body = '';
    foreach ($article['kernetekst'] as $div => $content) {
      $body .= $content . "\n";
    }
    // Only update the body text.
    $node->body['und'][0]['value'] = $body;
    node_save($node);
    // And we notify the user that the article has been updated.
    drupal_set_message(t('The microarticles have been updated'), 'status');
  }
  else {
    // We notify the user the exceptions or error.
    drupal_set_message(t('There was an error updating microarticles. Please try it later.'), 'status');
  }
  drupal_goto('node/' . $nid . '/edit');
}

/**
 * Implements hook_node_submit().
 */
function os2web_borger_dk_node_submit(&$node, $form, &$form_state) {
  if ($node->type == 'os2web_borger_dk_article') {
    // We must check if this is a "brand new" article or if it exists in the
    // database already (NB: That's how we find out if it is brand new or not)
    // Get the node->nid from the form['#node'].
    $nid = (!empty($form_state['values']['nid'])) ? $form_state['values']['nid'] : NULL;
    if (!empty($nid)) {
      // We have a node and should fetch field-values from form_state
      // nid, external_id, external_url, field_settings,
      // published_date, last_update.
      // EXCEPT: ONLY field_settings CAN BE UPDATED!!
      $field_settings = $form_state['values']['os2web_borger_dk_field_settings'];
      // Check admin field settings : are there fields set as hidden by admin.
      $admin_display_fields = variable_get('os2web_borger_dk_display');
      foreach ($admin_display_fields as $type => $items) {
        if (!$admin_display_fields[$type]) {
          $field_settings[$type] = $type;
        }
      }

      $serialized_data = serialize($field_settings);
      db_update('os2web_borger_dk_article')
        ->fields(array('field_settings' => $serialized_data))
        ->condition('nid', $nid, '=')
        ->execute();

      // Microarticles.---
      $microarticle = variable_get('os2web_borger_dk_microarticle_active');
      // If microarticle is set up to show.
      if ($microarticle) {
        $field_microarticle_settings = array();
        $body_text = isset($node->body['und'][0]['value']) ? $node->body['und'][0]['value'] : '';

        // "Link break": in windows \r\n, linux \n.
        preg_match("/<\/div>\n/", $body_text, $link_break);
        if (isset($link_break[0])) {
          $div = preg_split("/\n<\/div>\n/", $body_text, -1, PREG_SPLIT_DELIM_CAPTURE);
        }
        else {
          $div = preg_split('/\r\n<[\/]div>\r\n/', $body_text, -1, PREG_SPLIT_DELIM_CAPTURE);
        }

        $article_text = '';
        foreach ($div as $key => $text) {
          preg_match("/<div class=\"microArticle\" id=\"microArticle(.*?)\">/s", $div[$key], $match_id);
          $micro_id = (isset($match_id[1]) ? $match_id[1] : '');
          $microno = $key + 1;
          $checkboxno = 'os2web_borger_dk_micro_' . $microno;
          $h2_text_field = 'os2web_borger_dk_micro_h2_' . $microno;
          $text_area = 'os2web_borger_dk_micro_textarea_' . $microno;

          // The last div contents a link break.
          if ($key != (count($div) - 1)) {
            $field_microarticle_settings[$microno] = $node->$checkboxno;
            // Body text (Article text).
            $article_text .= "<div class=\"microArticle\" id=\"microArticle" . $micro_id . "\">" . "\r\n";

            $micro_h2 = "<h2 class=\"mArticle\" id=\"mArticle" . $microno . "\">";
            $micro_h2 .= $node->$h2_text_field . "</h2>";

            $micro_content = "<div class=\"mArticle" . $microno . " mArticle\">";
            $micro_content .= $node->$text_area . "\r\n    </div>";

            $article_text .= $micro_h2 . "\r\n";
            $article_text .= $micro_content;
            $article_text .= "\r\n</div>\r\n\r\n";
            // End of body text (Article text).
          }
        }
        $node->body['und'][0]['value'] = $article_text;
        $node->body['und'][0]['safe_value'] = $article_text;
        node_save($node);
        $serialized_microarticle = serialize($field_microarticle_settings);
        db_update('os2web_borger_dk_article')
          ->fields(array(
              'field_microarticle_settings' => $serialized_microarticle,
              ))
          ->condition('nid', $nid, '=')
          ->execute();
      }
      // End of Micro articles.
      // All other fields are handled by the normal Drupal field-handling.
    }
    else {
      // We do not(!) have a node->nid and this is a brand new node.
      // We must get the Borger.dk-URL, fetch the article, and store
      // the borger.dk-article content (i.e. the new node).
      $wsdl = variable_get('os2web_borger_dk_webservice', 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl');

      $titles_autocomplete = variable_get('borger_dk_article_titles_sync', FALSE);
      $borger_dk_url   = $form_state['values']['os2web_borger_dk_article_url_text'];
      $borger_dk_title = $form_state['values']['os2web_borger_dk_article_title_text'];
      $search_method   = $form_state['values']['os2web_borger_dk_article_title_search'];

      if ($search_method) {
        // The title has been autocompleted, and we must find the ArticleID.
        $matches = array();
        $aid = -1;
        // This preg_match() looks for the last pattern like [33334]
        // and if found extracts the numeric portion.
        $result = preg_match('/\(ID:([0-9]+)\)$/', $borger_dk_title, $matches);
        if ($result > 0) {
          // If $result is nonzero, we found a match and can use
          // it as the index into $matches.
          $aid = $matches[$result];
          $sql = "SELECT `ArticleID`, `ArticleStatus` FROM {os2web_borger_dk_article_titles} WHERE `ArticleID` = " . $aid . " LIMIT 1";
          $data = db_query($sql)->fetchObject();
          if ($data->ArticleStatus < 0) {
            // This article is no longer availlable and we tell the user so.
            drupal_set_message(t('The Borger.dk article with title "!title" is no longer availlable', array('!title' => $borger_dk_title)), 'warning');
            drupal_goto('node/add/os2web-borger-dk-article');
            return;
          }
          elseif ($data->ArticleStatus > 0) {
            // We have already imported this article
            // and node->nid = ArticleStatus.
            drupal_set_message(t('The Borger.dk article with title "!title" has already been imported.', array('!title' => $borger_dk_title)), 'status');
            drupal_set_message(t('You can re-import the article by clicking on the "Update now"-button below.'), 'status');
            drupal_goto('node/' . $data->ArticleStatus . '/edit');
            return;
          }
          elseif ($data->ArticleStatus == 0) {
            $aid = $data->ArticleID;
          }
        }
        else {
          // Lets look for the text directly in our Title list.
          drupal_set_message(t('No Borger.dk article with title "!title" exists.', array('!title' => $borger_dk_title)), 'warning');
          drupal_goto('node/add/os2web-borger-dk-article');
        }
        if (isset($aid) && $aid >= 0) {
          // We have not imported this article before, and we do so now.
          $article = _os2web_borger_dk_GetArticleByID($aid, $wsdl);
        }
        else {
          $borger_dk_title = preg_replace('/ \(ID:([0-9]+)\)$/', '', $borger_dk_title);
          drupal_set_message(t('Could not find any Borger.dk article with title "!title"', array('!title' => $borger_dk_title)), 'warning');
          drupal_goto('node/add/os2web-borger-dk-article');
          return;
        }
      }
      else {
        // Now we fetch the article item from the Borger.dk webservice.
        $article = _os2web_borger_dk_GetArticleByUrl($borger_dk_url, $wsdl);

        if (!empty($article['Exceptions']) || !empty($article['error'])) {
          drupal_set_message(t('An error occured or an exception was thrown by the Borger.dk webservice for the specified URL.'), 'error');
          drupal_set_message(t('You can fetch this article when the webservice is responsive again.'), 'error');
          drupal_goto('node/add/os2web-borger-dk-article');
          return;
        }
      }

      $body = '';
      foreach ($article['kernetekst'] as $div => $content) {
        $body .= $content . "\n";
      }

      // A user might assign the node author by entering a user name in the node
      // form, which we then need to translate to a user ID.
      if (isset($node->name)) {
        if ($account = user_load_by_name($node->name)) {
          $node->uid = $account->uid;
        }
        else {
          $node->uid = 0;
        }
      }

      // And we update all the node-fields with the article-values.
      $node = new stdClass();
      $node->created = !empty($node->date) ? strtotime($node->date) : REQUEST_TIME;
      $node->validated = TRUE;

      // Insert default value of a new node.
      $node->type = 'os2web_borger_dk_article';
      $node->title                                               = (!empty($article['title'])) ? $article['title'] : '';
      $node->body['und']['0']['value']                           = !empty($body) ? $body : '';
      $node->field_os2web_borger_dk_borgerurl['und'][0]['value'] = (!empty($article['external_url'])) ? $article['external_url'] : '';
      $node->field_os2web_borger_dk_header['und'][0]['value']    = (!empty($article['header'])) ? $article['header'] : '';
      $node->field_os2web_borger_dk_selfservi['und'][0]['value'] = (!empty($article['selvbetjeningslinks'])) ? $article['selvbetjeningslinks'] : '';
      $node->field_os2web_borger_dk_byline['und'][0]['value']    = (!empty($article['byline'])) ? $article['byline'] : '';
      $node->field_os2web_borger_dk_legislati['und'][0]['value'] = (!empty($article['lovgivning'])) ? $article['lovgivning'] : '';
      $node->field_os2web_borger_dk_shortlist['und'][0]['value'] = (!empty($article['huskeliste'])) ? $article['huskeliste'] : '';
      $node->field_os2web_borger_dk_recommend['und'][0]['value'] = (!empty($article['anbefaler'])) ? $article['anbefaler'] : '';

      $node->body['und']['0']['safe_value']                           = $body;
      $node->field_os2web_borger_dk_borgerurl['und'][0]['safe_value'] = (!empty($article['external_url'])) ? $article['external_url'] : '';
      $node->field_os2web_borger_dk_header['und'][0]['safe_value']    = (!empty($article['header'])) ? $article['header'] : '';
      $node->field_os2web_borger_dk_selfservi['und'][0]['safe_value'] = (!empty($article['selvbetjeningslinks'])) ? $article['selvbetjeningslinks'] : '';
      $node->field_os2web_borger_dk_byline['und'][0]['safe_value']    = (!empty($article['byline'])) ? $article['byline'] : '';
      $node->field_os2web_borger_dk_legislati['und'][0]['safe_value'] = (!empty($article['lovgivning'])) ? $article['lovgivning'] : '';
      $node->field_os2web_borger_dk_shortlist['und'][0]['safe_value'] = (!empty($article['huskeliste'])) ? $article['huskeliste'] : '';
      $node->field_os2web_borger_dk_recommend['und'][0]['safe_value'] = (!empty($article['anbefaler'])) ? $article['anbefaler'] : '';

      $node->body['und'][0]['format']                             = 'full_html';
      $node->field_os2web_borger_dk_header['und'][0]['format']    = 'full_html';
      $node->field_os2web_borger_dk_selfservi['und'][0]['format'] = 'full_html';
      $node->field_os2web_borger_dk_byline['und'][0]['format']    = 'plaintext';
      $node->field_os2web_borger_dk_legislati['und'][0]['format'] = 'full_html';
      $node->field_os2web_borger_dk_shortlist['und'][0]['format'] = 'full_html';
      $node->field_os2web_borger_dk_recommend['und'][0]['format'] = 'full_html';

      $field_settings = $form_state['values']['os2web_borger_dk_field_settings'];
      // Check admin field settings : are there fields set as hidden by admin.
      $admin_display_fields = variable_get('os2web_borger_dk_display');
      foreach ($admin_display_fields as $type => $items) {
        if (!$admin_display_fields[$type]) {
          $field_settings[$type] = $type;
        }
      }
      // TODO: Perform a logical-test (on paper) to
      // see if the external_status is correct.
      $external_status = (empty($article['Exceptions']) && empty($article['error'])) ? 1 : 0;
      $external_status = (!empty($article['error']) && $article['error_type'] == 'not_found') ? -1 : $external_status;
      $node->os2web_borger_dk_article = array(
        'external_id'     => $article['external_id'],
        'external_url'    => $article['external_url'],
        'external_status' => $external_status,
        'field_settings'  => $field_settings,
        'published_date'  => strtotime($article['published_date']),
        'last_updated'    => strtotime($article['last_updated']),
      );

      if (!empty($article['Exceptions']) || !empty($article['error'])) {
        drupal_set_message(t('An exception was thrown by the Borger.dk webservice for the specified URL.'), 'error');
        drupal_set_message(t('You can fetch this article when the webservice is responsive again.'), 'error');
        drupal_goto('node/add/os2web-borger-dk-article');
      }
      else {
        $node = node_submit($node);

        // We need to store the field values and article-settings.
        node_save($node);

        // Then we need to update the ArticleStatus in the Title-list.
        if ($node->nid) {
          db_update('os2web_borger_dk_article_titles')
            ->fields(array('ArticleStatus' => $node->nid))
            ->condition('ArticleID', $article['external_id'], '=')
            ->execute();
          drupal_goto('node/' . $node->nid . '/edit');
        }
      }
    }
  }
}

/**
 * Implements hook_cron().
 */
function os2web_borger_dk_cron() {
  $cron_settings_time_articles = variable_get('os2web_borger_dk_nightly_article_sync', FALSE);
  $titles_autocomplete = variable_get('os2web_borger_dk_titles_sync', FALSE);
  $borger_dk_menus_import = variable_get('os2web_borger_dk_menus_import', FALSE);
  $cron_settings_time_menus = variable_get('os2web_borger_dk_nightly_menu_sync');

  // Then we can find out if it is time for our cron-job to run.
  if (!empty($cron_settings_time_articles) || !empty($cron_settings_time_menus)) {
    $current_time = time();
    $current_hour = date('G', $current_time);
    if ($current_hour == '0') {
      $current_hour = '24';
    }

    // Is it time for auto-updating imported Borger.dk-articles.
    if ($cron_settings_time_articles == $current_hour) {
      // Run the auto-update for articles already imported.
      _os2web_borger_dk_cronbatch();

      // Fetch availlable Borger.dk-titles if autocomplete has been activated.
      if ($titles_autocomplete) {
        // We must fetch a list of all availlable articles from Borger.dk.
        _os2web_borger_dk_titles_cronbatch();
      }
    }

    // Is it time for auto-updating imported Borger.dk-menus.
    if ($cron_settings_time_menus == $current_hour) {
      $this_run = time();
      $last_run = variable_get('os2web_borger_dk_menus_last_update', $this_run);
      $weekly = variable_get('os2web_borger_dk_weekly_borger_dk_menus_import', 0);
      // 7 * 24 * 60 * 60 = 604800. We deduct 800 seconds to give the cron-request
      // some time to start.
      if (!empty($weekly) && ($this_run - $last_run > 604000)) {
        // It is "about" a week ago now, so we start the cronbatch-job now.
        _os2web_borger_dk_menus_cronbatch();
      }
      else if (empty($weekly)) {
        // If run daily then we start the cronbatch-job now.
        _os2web_borger_dk_menus_cronbatch();
      }
    }
  }

  // We check for deleted-items in the queue at every cron-run.
  _os2web_borger_dk_cron_queue();
}

/**
 * Function _os2web_borger_dk_menus_cronbatch()
 */
function _os2web_borger_dk_menus_cronbatch($force_update = FALSE) {
  $this_run = time();
  $last_run = variable_get('os2web_borger_dk_menus_last_update', $this_run);

  $wsdl = variable_get('os2web_borger_dk_webservice', 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl');
  $menu_items_availlable = _os2web_borger_dk_GetAllSites($wsdl);
  $my_menu = array();
  $errors = array();

  if (!empty($menu_items_availlable['Exceptions']) || !empty($menu_items_availlable['error'])) {
    $updated_at = date('Y-m-d\TH\:i\:s', $last_run);
    $msg = 'An error occured while fetching the Borger.dk menus. Last succesful update was at: %success';
    watchdog('Borger.dk-articles', $msg, $variables = array('%success' => $updated_at));
    return;
  }

  // Now we step through all the menu-items and put them into a menu-structure.
  foreach ($menu_items_availlable as $item) {
    $result = _os2web_borger_dk_build_borger_dk_menustructure($my_menu, $item);
    if (!$result) {
      $errors[] = array(
        'item' => $item,
        'error' => 'Could not find parent menu-item. Item not inserted into menu-structure',
      );
    }
  }

  // If no errors occured we create Drupal-menus from the menu-structure.
  if (empty($errors)) {
    // Before we update the Borger.dk-menu we must check if it has changed
    // from last time we updated it.

    $old_value = variable_get('os2web_borger_dk_old_menu_structure');
    if ($force_update) {
      $old_value = '';
    }

    $new_value = serialize($my_menu);
    if ($old_value != $new_value) {
      variable_set('os2web_borger_dk_old_menu_structure', $new_value);

      _os2web_borger_dk_menus_create_items($my_menu);

      // Finally we update the timestamp for when our last succesfull menu-
      // update took place (that would be now).
      variable_set('os2web_borger_dk_menus_last_update', $this_run);
    }
    else {
      $updated_at = date('Y-m-d\TH\:i\:s', $last_run);
      $msg = 'No updates: Tried to update the Borger.dk menus but found that it has not changed since last succesful update at: %success';
      watchdog('Borger.dk-articles', $msg, $variables = array('%success' => $updated_at));
    }
  }
  else {
    $updated_at = date('Y-m-d\TH\:i\:s', $last_run);
    $msg = 'One or more errors occured while building the new Borger.dk menu-structure locally. Last succesful update was at: %success. Listing errors in watchdog.';
    watchdog('Borger.dk-articles', $msg, $variables = array('%success' => $updated_at));
    foreach ($errors as $error) {
      $msg = 'Could not find the parent item in the Borger.dk-menu for this Borger.dk-menu item: '. print_r($error['item'], TRUE) ."\n";
      watchdog('Borger.dk-articles', $msg);
    }
  }
}

/**
 * Function _os2web_borger_dk_forms_cronbatch()
 */
function _os2web_borger_dk_forms_cronbatch($force_update = FALSE) {
  $this_run = time();
  $last_run = variable_get('os2web_borger_dk_form_last_update', $this_run);
  $form_menu_vid = variable_get('os2web_borger_dk_form_menu_vid', FALSE);
  $other_term_tid = variable_get('os2web_borger_dk_form_menu_tid_other', FALSE);
  $tag_articles = variable_get('os2web_borger_dk_form_autotagging', $force_update);
  $errors = array();

  if (($force_update) || FALSE === $form_menu_vid) {
    // Let us find the vocabulary id, and store it for good.
    $form_menu_vid = db_query("SELECT vid FROM {taxonomy_vocabulary} WHERE machine_name LIKE :menu_name", array(':menu_name' => 'os2web_borger_dk_form_menu'))->fetchField();
    variable_set('os2web_borger_dk_form_menu_vid', $form_menu_vid);
    // We must also check if the "Other"-taxonomy-term exists.
    $title = t("Miscellaneous links");
    $item_check = _os2web_borger_dk_check_form_taxonomy_item($title, $title, $form_menu_vid);
    if ($item_check === FALSE) {
      // The 'Other' taxonomy-term does not exist and we create it.
      //$log .= '=> (Check-result === FALSE)'."\n".'-> Calling : _os2web_borger_dk_insert_form_taxonomy_item() for uuid: '. $form_uuid ."\n";
      $other_term_tid = _os2web_borger_dk_insert_form_taxonomy_item($title, $title, $form_menu_vid, NULL, 50);
      //$log .= '=> Got new term-tid: '. $term_tid ."\n";
      drupal_set_message('Got new "Other" term-tid: '. $other_term_tid .', for term-title: '. $title .', in vocabulary vid: '. $form_menu_vid);
      variable_set('os2web_borger_dk_form_menu_tid_other', $other_term_tid);
    }
    else {
      $other_term_tid = $item_check->tid;
      variable_set('os2web_borger_dk_form_menu_tid_other', $other_term_tid);
      drupal_set_message('Got existing "Other" term-tid: '. $other_term_tid .', for term-title: '. $title .', term: <pre>'. print_r($item_check, TRUE) .'</pre>');
    }
  }

  return;

  $old_form_serialized = variable_get('os2web_borger_dk_old_form_structure', FALSE);
  if ($force_update || (FALSE === $old_form_serialized)) {
    $old_form_serialized = '';
    // First we fetch the top level form-elements.
    $service_areas_list_xml = file_get_contents('http://www.form-online.dk:8080/FORM-REST/resources/?dybde=0');
    // Before we go any further we check if we got an error or not.
    if ($service_areas_list_xml === FALSE) {
      $errors[] = array(
        'error' => 'Could not get the top-level FORM menu from: http://www.form-online.dk:8080/FORM-REST/resources/?dybde=0',
      );
    }
    else {
      // Then we can convert the fetched list into an XML document.
      $service_areas_doc = new DOMDocument('1.0', 'UTF-8');
      $service_areas_doc->strictErrorChecking = FALSE;
      $service_areas_doc->loadXML($service_areas_list_xml);
      $service_areas_xml = simplexml_import_dom($service_areas_doc);

      // Now we must convert the service_areas_xml to a nicely formatted array.
      $service_areas_array = _os2web_borger_dk_build_form_service_areas($service_areas_xml);

      // Then we can fetch the sub-level form-elements.
      $form_task_list_xml = file_get_contents('http://www.form-online.dk:8080/FORM-REST/resources/?dybde=4');
      // Before we go any further we check if we got an error or not.
      if ($form_task_list_xml === FALSE) {
        $errors[] = array(
          'error' => 'Could not get the top-level FORM menu from: http://www.form-online.dk:8080/FORM-REST/resources/?dybde=0',
        );
      }
      else {
        // Next we convert the form_task_list_xml to a nicely formatted array.
        $services_doc = new DOMDocument('1.0', 'UTF-8');
        $services_doc->strictErrorChecking = FALSE;
        $services_doc->loadXML($form_task_list_xml);
        $services_xml = simplexml_import_dom($services_doc);

        // Then we merge the two arrays to create the total FORM-menu structure.
        _os2web_borger_dk_build_form_services_list($service_areas_array, $services_xml);
        $new_value = serialize($service_areas_array);
        if ($force_update || ($old_form_serialized != $new_value)) {
          variable_set('os2web_borger_dk_old_form_structure', $new_value);

          // Now we can check/create the taxonomies found in the FORM-Services.
          _os2web_borger_dk_check_form_service_taxonomies($service_areas_array, $form_menu_vid);

          if ($tag_articles) {
            // Should imported Borger.dk-articles be tagged automatically using
            // the os2web_borger_dk_form_menu-taxonomy.
            $wsdl = variable_get('os2web_borger_dk_webservice', 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl');
            $titles_availlable = _os2web_borger_dk_GetAllArticles($wsdl);

            if (!empty($titles_availlable['Exceptions']) || !empty($titles_availlable['error'])) {
              $updated_at = date('Y-m-d\TH\:i\:s', $last_run);
              $msg = 'An error occured while fetching the Borger.dk menus. Could not tag imported articles. Last succesful update was at: %success';
              watchdog('Borger.dk-articles', $msg, $variables = array('%success' => $updated_at));
            }
            else {
              // No errors occured and we can proceed to tag all the Borger.dk-
              // imported articles with the FORM-taxonomy.
              // First we get a list of imported-articles.
              $update_items = array();
              $sql = 'SELECT n.nid, ba.external_id FROM {node} AS n LEFT JOIN {os2web_borger_dk_article} AS ba ON n.nid = ba.nid WHERE n.type LIKE :node_type AND n.status = 1';
              $result = db_query($sql, array(':node_type' => 'os2web_borger_dk_article'));
              foreach ($result as $record) {
                $update_items[$record->external_id] = $record->nid;
              }
              //$log = '_os2web_borger_dk_forms_cronbatch found this list of articles to tag: '. print_r($update_items, TRUE) ."\n===================\n";
              //error_log($log ."\n\n", 3, '/home/peter/bellcom/log/debug_form_kle_5.log');
              _os2web_borger_dk_form_tag_borger_dk_articles($form_menu_vid, $titles_availlable, $update_items, $other_term_tid);
            }
          }
        }
      }
    }
  }

  if (!empty($errors)) {
    $updated_at = date('Y-m-d\TH\:i\:s', $last_run);
    $msg = 'One or more errors occured while building the new Borger.dk FORM taxonomies locally. Last succesful update was at: %success. Listing errors in watchdog.';
    watchdog('Borger.dk-articles', $msg, $variables = array('%success' => $updated_at));
    foreach ($errors as $error) {
      watchdog('Borger.dk-articles', $error['error'] ."\n");
    }
  }
  else {
    // Finally we update the timestamp for when our last succesfull menu-
    // update took place (that would be now).
    variable_set('os2web_borger_dk_form_last_update', $this_run);
    $updated_at = date('Y-m-d\TH\:i\:s', $this_run);
    $msg = 'Succesfully updated/created the Borger.dk FORM taxonomies locally. Update occured at: %success';
    watchdog('Borger.dk-articles', $msg, $variables = array('%success' => $updated_at));
  }
}

function _os2web_borger_dk_check_form_service_taxonomies($form_service_list, $vid, $ptid = NULL, $level = 0) {
  //$log = '_os2web_borger_dk_check_form_service_taxonomies(service_list, vid, ptid, level)::[array(), '. $vid .', '. $ptid .', '. $level .'] started.'."\n";
  $levels = array(
    0 => 'ServiceOmraade',
    1 => 'HovedOmraade',
    2 => 'OpgaveOmraade',
    3 => 'Opgave',
  );
  $nlname = ($level < 3) ? ($levels[$level + 1]) : FALSE;
  foreach ($form_service_list as $form_uuid => $form_item) {
    $item_name = $form_item['NavnTekst'];
    //$log .= '-> Checking item (Uuid, NavnTekst): ('. $form_uuid .', '. $item_name .")\n";
    $item_check = _os2web_borger_dk_check_form_taxonomy_item($form_uuid, $item_name, $vid, $ptid);
    if ($item_check === FALSE) {
      // The taxonomy-term does not exist and we create it.
      //$log .= '=> (Check-result === FALSE)'."\n".'-> Calling : _os2web_borger_dk_insert_form_taxonomy_item() for uuid: '. $form_uuid ."\n";
      $term_tid = _os2web_borger_dk_insert_form_taxonomy_item($form_uuid, $item_name, $vid, $ptid);
      //$log .= '=> Got new term-tid: '. $term_tid ."\n";
    }
    else {
      // The taxonomy-term does exist and we use the tid as parent tid for
      // any and all children.
      $term_tid = $item_check->tid;
    }
    // If this item has children those must be checked as well.
    if (($level < 3) && (isset($form_item[$nlname]) && is_array($form_item[$nlname]))) {
      //$log .= '-> Going recursive on level : '. $nlname ."\n===================\n";
      //error_log($log ."\n\n", 3, '/home/peter/bellcom/log/debug_form_kle_5.log');
      //$log = '';
      _os2web_borger_dk_check_form_service_taxonomies($form_item[$nlname], $vid, $term_tid, 1 + $level);
    }
    else {
      //$log .= '-> No children on this level: ==> form_item: '. print_r($form_item, TRUE) ."\n===================\n";
      //error_log($log ."\n\n", 3, '/home/peter/bellcom/log/debug_form_kle_5.log');
      //$log = '';
    }
  }
}

function _os2web_borger_dk_check_form_taxonomy_item($uuid, $name, $vid, $ptid = NULL) {
  $check = FALSE;
  //$log = '_os2web_borger_dk_check_form_taxonomy_item. For uuid,vid,name: '. $uuid .', '. $vid .', '. $name ."\n";
  $term_result = taxonomy_get_term_by_name($name, 'os2web_borger_dk_form_menu');
  if (!empty($term_result)) {
    foreach($term_result as $tid => $term) {
      if (($vid == $term->vid) && ($uuid == $term->description)) {
        $check = $term;
        //$log .= '==> FOUND term: '. print_r($term, TRUE) ."\n\n";
        break;
      }
    }
  }
  //error_log($log, 3, '/home/peter/bellcom/log/debug_form_kle_5.log');

  return $check;
}

function _os2web_borger_dk_insert_form_taxonomy_item($uuid, $name, $vid, $ptid = NULL, $weight = NULL) {
  $term = new stdClass();
  $term->vid = $vid;
  $term->name = trim($name);
  $term->description = $uuid;

  // If a parent tid is given we must set that too.
  if (isset($ptid)) {
    $term->parent = $ptid;
  }

  // If a weight is given we must also set that.
  if (isset($weight)) {
    $term->weight = $weight;
  }

  // Then we can insert the new taxonomy term.
  taxonomy_term_save($term);
  //error_log('_os2web_borger_dk_insert_form_taxonomy_item(). saved this term: '. print_r($term, TRUE) ."\n\n", 3, '/home/peter/bellcom/log/debug_form_kle_5.log');

  // We return the tid of the newly created term.
  return $term->tid;
}

function os2web_borger_dk_debug_form_submit($form, &$form_state) {
  // 1) Use this function to delete the Borger.dk-menu:
  //_debug_remove_add_menu();

  // 2) Use these functions to test the cronjobs:
  if (($form_state['submitted'] == 1) && ($form_state['input']['op'] == 'Debug Cron Borger.dk-Menu now')) {
    _os2web_borger_dk_menus_cronbatch(TRUE);
  }
  if (($form_state['submitted'] == 1) && ($form_state['input']['op'] == 'Debug Cron FORM-taxonomies now')) {
    _os2web_borger_dk_forms_cronbatch(TRUE);
  }

  drupal_goto('admin/borgerdk/debug');
}

function _debug_remove_add_menu() {
  $del_menu = menu_load('menu-borger-dk-articles-menu');
  if ($del_menu) {
    menu_delete($del_menu);
  }
  // Then we create the top-level menu-item (again).
  $menu_title = variable_get('os2web_borger_dk_borger_dk_menu_name', 'Borger.dk menu');
  $new_menu = array(
    'menu_name' => 'menu-borger-dk-articles-menu',
    'title' => $menu_title,
    'description' => 'The full menu from Borger.dk',
  );
  menu_save($new_menu);
}

/**
 * Function _os2web_borger_dk_build_form_service_areas()
 */
function _os2web_borger_dk_build_form_service_areas($areas_xml) {
  $areas = array();
  foreach ($areas_xml->ServiceOmraade as $obj) {
    $name = $obj->NavnTekst;
    $id = $obj->UuidIdentifikator;
    $areas["$id"] = array();
    $areas["$id"]['NavnTekst'] = (string) $name;
  }

  return $areas;
}

/**
 * Function _os2web_borger_dk_build_form_services_list()
 */
function _os2web_borger_dk_build_form_services_list(&$service_areas, $services) {
  foreach ($services->ServiceOmraade as $obj) {
    $name = (string) $obj->NavnTekst;
    $id = (string) $obj->UuidIdentifikator;
    if (!empty($service_areas["$id"])) {
      $service_areas["$id"]['HovedOmraade'] = array();
      $my_services_list = _os2web_borger_dk_build_form_services_sub_list($obj, 1);
      $service_areas["$id"]['HovedOmraade'] = $my_services_list;
    }
  }
}

/**
 * Function _os2web_borger_dk_build_form_services_sub_list()
 */
function _os2web_borger_dk_build_form_services_sub_list($obj, $level = 0) {
  $levels = array(
    0 => 'ServiceOmraade',
    1 => 'HovedOmraade',
    2 => 'OpgaveOmraade',
    3 => 'Opgave',
  );

  $sub_list = array();
  $lname = $levels[$level];
  if (isset($obj->{"$lname"})) {
    foreach ($obj->{"$lname"} as $sub_obj) {
      $name = (string) $sub_obj->NavnTekst;
      $id = (string) $sub_obj->UuidIdentifikator;
      $sub_list["$id"] = array();
      $sub_list["$id"]['NavnTekst'] = $name;
      if ($level < 3) {
        $sub_level = $levels[$level + 1];
        $sub_list["$id"][$sub_level] = _os2web_borger_dk_build_form_services_sub_list($sub_obj, $level + 1);
      }
    }
  }

  return $sub_list;
}

/**
 * Function _os2web_borger_dk_menus_create_items().
 */
function _os2web_borger_dk_menus_create_items($menu_items) {
  // First we find all the old menus and menu-links.
  $del_menu = menu_load('menu-borger-dk-articles-menu');
  if ($del_menu) {
    $old_menu = menu_tree_all_data('menu-borger-dk-articles-menu');
  }
  $old_links = array();
  $old_mlid_other = variable_get('os2web_borger_dk_not_found_menu_mlid', 0);

  if (($del_menu) && (isset($old_menu) && !empty($old_menu))) {
    // Find the old "Miscellaneous links" mlid
    // A menu already exists and we must delete it after having found all
    // the associated menu-links (these must be moved to the new menu).
    _os2web_borger_dk_menus_find_links($old_links, $old_menu, 'menu-borger-dk-articles-menu');

    // Now we can delete the "old" menu.
    menu_delete($del_menu);
  }

  // Then we create the top-level menu-item (again).
  $menu_title = variable_get('os2web_borger_dk_borger_dk_menu_name', 'Borger.dk menu');
  $new_menu = array(
    'menu_name' => 'menu-borger-dk-articles-menu',
    'title' => $menu_title,
    'description' => 'The full menu from Borger.dk',
  );
  menu_save($new_menu);

  // Then we insert all the Borger.dk-menu-items into the new menu.
  $mlid_index = array();
  _os2web_borger_dk_insert_menu_links($menu_items[1]['children'], $mlid_index, 0, 'menu-borger-dk-articles-menu');

  // If any "old-links" were found we must insert those into the new menu.
  if (!empty($old_links['children'])) {
    // And we insert an extra menu-item called 'Other' for links we
    // can not find a position for in the menu.
    $my_link = array(
      'link_path'  => '<nolink>',
      'link_title' => t("Miscellaneous links"),
      'menu_name'  => 'menu-borger-dk-articles-menu',
      'weight'     => 50,
    );
    // Then we save the link-item.
    $mlid_other = menu_link_save($my_link);
    variable_set('os2web_borger_dk_not_found_menu_mlid', $mlid_other);

    // Insert old_links into new menu-structure.
    _os2web_borger_dk_merge_links_into_menu($old_links['children'], $mlid_index, 0, $mlid_other, $old_mlid_other);
  }
}

function _os2web_borger_dk_merge_links_into_menu($menu_links, $mlid_index, $plid = 0, $not_found_mlid, $old_not_found_mlid) {
  foreach ($menu_links as $id => $litem) {
    $my_link = array(
      'link_path'  => $litem['link_path'],
      'link_title' => $litem['link_title'],
      'menu_name'  => $litem['menu_name'],
      'weight'     => $litem['weight'],
      'expanded'   => $litem['expanded'],
      'options'    => $litem['options'],
      'hidden'     => $litem['hidden'],
    );

    // If we know the parent mlid (called plid) we use that.
    if ($plid > 0) {
      $my_link['plid'] = $plid;
    }

    // Now we try to find the matching menu-item.
    if (isset($litem['mlid']) && $litem['mlid'] == $old_not_found_mlid) {
      // This is the old "Miscellaneous links" menu-item
      $my_link['mlid'] = $not_found_mlid;
      // This link does not get saved. Instead we use the mlid
      // for each of the children (if any).
      $mlid = $not_found_mlid;
    }
    else {
      // Try to find the mlid among the known nlid's.
      $mlid = _os2web_borger_dk_find_known_mlid($litem['link_title'], $mlid_index);
      if ($mlid) {
        // Then it is an existing menu-item we must update.
        $my_link['mlid'] = $mlid;
      }
      else {
        // mlid not found! If we do not have a plid then this menu-link can not
        // be placed in the menu and must be put into the 'Other'-menu-group.
        if ($plid == 0) {
          $my_link['plid'] = $not_found_mlid;
        }
      }
      // Now we can save the link-item.
      $mlid = menu_link_save($my_link);
    }

    // And if this link_item has children they must be inserted as well.
    if (isset($litem['children']) && is_array($litem['children'])) {
      _os2web_borger_dk_merge_links_into_menu($litem['children'], $mlid_index, $mlid, $not_found_mlid, $old_not_found_mlid);
    }
  }
}

function _os2web_borger_dk_find_known_mlid($menu_name, $mlid_index) {
  $found = FALSE;
  foreach ($mlid_index as $id => $name) {
    if ($menu_name == $name) {
      $found = $id;
      break;
    }
  }
  return $found;
}

function _os2web_borger_dk_insert_menu_links($links, &$index, $plid = 0, $menu_name = 'menu-borger-dk-articles-menu') {
  foreach ($links as $id => $link_item) {
    $link_title = $link_item['SiteTitle'];
    // First we create the "empty" link-item.
    $my_link = array(
      'link_path'  => '<nolink>',
      'link_title' => $link_title,
      'menu_name'  => $menu_name,
    );
    // If a parent (plid) is given we also use that to place the links correct.
    if ($plid > 0) {
      $my_link['plid'] = $plid;
    }
    // Then we save the link-item.
    $mlid = menu_link_save($my_link);
    // And if it was saved OK then we remember the mlid.
    if ($mlid) {
      $index[$mlid] = $link_title;
      // If this item has children we insert those now
      if (isset($link_item['children']) && is_array($link_item['children'])) {
        _os2web_borger_dk_insert_menu_links($link_item['children'], $index, $mlid, $menu_name);
      }
    }
  }
}

function _os2web_borger_dk_menus_find_links(&$links, $menu = array(), $menu_name = 'menu-borger-dk-articles-menu') {
  //We must step through all menu-items in order to find menu-links.
  if (is_array($menu)) {
    foreach ($menu as $id => $item) {
      // Check if this level has a 'link'-item.
      if (isset($item['link'])) {
        $plid = $item['link']['plid'];
        $mlid = $item['link']['mlid'];
        $my_link = array(
          'link_path'  => $item['link']['link_path'],
          'link_title' => $item['link']['link_title'],
          'menu_name'  => $menu_name,
          'weight'     => $item['link']['weight'],
          'expanded'   => $item['link']['expanded'],
          'options'    => $item['link']['options'],
          'mlid'       => $mlid,
          'plid'       => $plid,
          'hidden'     => $item['link']['hidden'],
        );
        if ($plid == 0) {
          // This is a "top-level" menu-link
          if (isset($links['children']) && is_array($links['children'])) {
            $links['children'][$mlid] = $my_link;
          }
          else {
            $links['children'] = array();
            $links['children'][$mlid] = $my_link;
          }
        }
        else {
          // Find the link-item to insert the new item under.
          _os2web_borger_dk_insert_old_menu_link($links, $my_link);
        }
      }
      // Then we find "next-level"-links
      if (isset($item['below']) && !empty($item['below'])) {
        _os2web_borger_dk_menus_find_links($links, $item['below'], $menu_name);
      }
    }
  }
}

function _os2web_borger_dk_insert_old_menu_link(&$links, $item, $menu_name = 'menu-borger-dk-articles-menu') {
  if (is_array($links['children'])) {
    $plid = $item['plid'];
    $mlid = $item['mlid'];
    if (isset($links['children'][$plid])) {
      // The link-item exists on this level, and we insert the link-item.
      if (isset($links['children'][$plid]['children']) && is_array($links['children'][$plid]['children']))
        $links['children'][$plid]['children'][$mlid] = $item;
      else {
        $links['children'][$plid]['children'] = array();
        $links['children'][$plid]['children'][$mlid] = $item;
      }
      return TRUE;
    }
    else {
      // We must search for the parent item in the list
      foreach ($links['children'] as $id => $link_item) {
        // We only look at sub_levels with numeric keys
        if (!is_numeric($id)) {
          continue;
        }
        // Check if the ParentID-key is defined at this level
        if (isset($link_item['children'][$plid])) {
          if (isset($link_item['children'][$plid]['children']) && is_array($link_item['children'][$plid]['children'])) {
            $links['children'][$id]['children'][$plid]['children'][$mlid] = $item;
          }
          else {
            $links['children'][$id]['children'][$plid]['children'] = array();
            $links['children'][$id]['children'][$plid]['children'][$mlid] = $item;
          }
          //$links[$id][$plid][$mlid] = $item;
          return TRUE;
        }
        else {
          if (is_array($link_item['children'])) {
            $result = _os2web_borger_dk_insert_old_menu_link($link_item, $item);
            if ($result) {
              // If a result was found we store the new sub_level in the menu
              $links['children'][$id] = $link_item;
              return TRUE;
            }
          }
        }
      }
    }
  }

  return FALSE;
}

/**
 * Function _os2web_borger_dk_cron_queue().
 */
function _os2web_borger_dk_cron_queue() {
  $queue = DrupalQueue::get('os2web_borger_dk_delete_queue');
  $result = db_query('SELECT nid, external_id FROM {os2web_borger_dk_article} WHERE external_status = -2');
  foreach ($result as $item) {
    $qitem = array('nid' => $item->nid, 'external_id' => $item->external_id);
    $queue->createItem($qitem);
  }
}

/**
 * Function _os2web_borger_dk_cronbatch().
 */
function _os2web_borger_dk_cronbatch() {
  // First we determine the time for our last check for new updates.
  $this_run = time();
  $last_run = variable_get('os2web_borger_dk_last_update', time());
  $updated_after = date('Y-m-d\TH\:i\:s', $last_run);
  $titles_autocomplete = variable_get('os2web_borger_dk_titles_sync', FALSE);

  // Next we get a list of all imported articles.
  $article_id_list = array();
  $article_id_to_nid = array();
  $result = db_query('SELECT nid, external_id FROM {os2web_borger_dk_article} WHERE external_status > 0');
  foreach ($result as $item) {
    // We also build an index of "external_id" => "nid".
    $article_id2nid[$item->external_id] = $item->nid;
    $article_id_list[] = $item->external_id;
  }

  // Then we get all the updated articles. We can not(!) use the LastUpdated-
  // field in the 'os2web_borger_dk_titles'-table since it only works when
  // titles-autocomplete has been activated.
  $articles = array();
  $wsdl = variable_get('os2web_borger_dk_webservice', 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl');
  $articles = _os2web_borger_dk_GetArticlesByIDs($article_id_list, $updated_after, $wsdl);

  // We must check if the webservice throws ANY errors.
  $any_webservice_errors = FALSE;
  // $deleted_items = array();
  $deleted_ids = array();
  $error_items = array();
  // And for each of the found articles we update the node content.
  foreach ($articles as $article) {
    $external_id = $article['external_id'];
    // We only update articles we already know the nid for (just in case).
    if (!empty($article_id2nid[$external_id])) {
      $nid = $article_id2nid[$external_id];

      // First we check if the article is an error-array.
      if (empty($article['no_updates'])) {
        // We only update articles that does not contain an error.
        if (empty($article['Exceptions']) && empty($article['error'])) {
          _os2web_borger_dk_update_node_content($nid, $article);
        }
        if (!empty($article['Exceptions'])) {
          $any_webservice_errors = TRUE;
        }
      }
      else {
        // Articles with errors might have been deleted, and we must handle it.
        // But if "Titles autocomplete" is active, then it will be handled by
        // the titles-auto-update in the cron-function:
        // _os2web_borger_dk_titles_cronbatch().
        if (!$titles_autocomplete) {
          // Try to get this one article, to see if it still exists.
          $item = _os2web_borger_dk_GetArticleByID($external_id, $wsdl);
          if (!empty($item['error']) && $item['error'] == 1) {
            if (!empty($item['error_type']) && ($item['error_type'] == 'not_found')) {
              // $deleted_items[$nid] = $item;
              $deleted_ids[] = $nid;
            }
            else {
              $error_items[$nid] = $item;
            }
          }
        }
      }
    }
  }

  // Next we update/queue the articles that should be deleted.
  // Deleted_ids will only contain elements
  // if "Titles autocomplete" is inactive.
  if (!empty($deleted_ids)) {
    $sql = "UPDATE {os2web_borger_dk_article} SET external_status = -2 WHERE nid IN (:nids)";
    $nid_list = implode(',', $deleted_ids);
    db_query($sql, array(':updated' => $this_run, ':nids' => $nid_list));
  }

  // Then we log the errors that occured but we could not handle.
  if (!empty($error_items)) {
    foreach ($error_items as $nid => $error) {
      $msg = 'Borger.dk webservice returned an error for nid=%nid, external_id=%eid. Error code: %ecode. Error string: %estring';
      watchdog(
        'OS2web Borger.dk',
        $msg,
        $variables = array(
          '%nid' => $nid,
          '%eid' => $error['external_id'],
          '%ecode' => $error['error_code'],
          '%estring' => $error['error_string'])
      );
    }
  }

  // Now we must update the "last_updated" variable.
  // But only if no errors were encountered.
  if (!$any_webservice_errors) {
    variable_set('os2web_borger_dk_last_update', $this_run);
    $updated_at = date('Y-m-d\TH\:i\:s', $this_run);
    $msg = 'All Borger.dk webservice articles have been updated succesfully at: %success';
    watchdog('OS2web Borger.dk', $msg, $variables = array('%success' => $updated_at));
  }
  else {
    $should_have_been = date('Y-m-d\TH\:i\:s', $this_run);
    $msg = 'Borger.dk webservice threw errors while updating articles at: %runtime. Not all articles have been updated. Last succesful automated update was at: %success';
    watchdog('OS2web Borger.dk', $msg, $variables = array('%runtime' => $should_have_been, '%success' => $updated_after));
  }
}

/**
 * Function _os2web_borger_dk_titles_cronbatch().
 */
function _os2web_borger_dk_titles_cronbatch($first_run = FALSE) {
  $borger_dk_menus_import = variable_get('os2web_borger_dk_menus_import', FALSE);
  $titles_availlable = array();
  $wsdl = variable_get('os2web_borger_dk_webservice', 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl');
  $titles_availlable = _os2web_borger_dk_GetAllArticles($wsdl);

  // We must update the table of Borger.dk Article titles.
  // And to do that we must know what is already there, so that we can mark
  // un-listed titles for deletion.
  $titles_result = db_query('SELECT `ArticleID`, `ArticleStatus`, `LastUpdated` FROM {os2web_borger_dk_article_titles} WHERE `ArticleStatus` >= 0');
  $known_ids = array();
  foreach ($titles_result as $item) {
    $aid = $item->ArticleID;
    $known_ids[$aid] = array('ArticleStatus' => $item->ArticleStatus, 'LastUpdated' => $item->LastUpdated);
  }

  foreach ($titles_availlable as $id => $item) {
    $aid = $item['ArticleID'];
    // Check the known status (if any).
    if (isset($known_ids[$aid])) {
      // Before we update we check if it has been changed.
      $updated = strtotime($item['LastUpdated']);
      if ($updated > $known_ids[$aid]['LastUpdated']) {
        // We know about this article and we update the DB-entry
        // because the content has changed since we updated it last.
        db_update('os2web_borger_dk_article_titles')
          ->fields(array(
            'ArticleTitle' => $item['ArticleTitle'],
            'ArticleUrl'   => $item['ArticleUrl'],
            'LastUpdated'  => $updated,
            'FORMFields'   => $item['FORMFields'],
          ))
          ->condition('ArticleID', $aid, '=')
          ->execute();
      }
      // We remove this item from the list of known ID's so that we can
      // find out if all the known ID's were found in the list.
      unset($known_ids[$aid]);
    }
    else {
      // This is a new article-title and we must insert it into DB.
      db_insert('os2web_borger_dk_article_titles')
        ->fields(array(
          'ArticleID'      => $aid,
          'ArticleTitle'   => $item['ArticleTitle'],
          'ArticleUrl'     => $item['ArticleUrl'],
          'LastUpdated'    => strtotime($item['LastUpdated']),
          'PublishingDate' => strtotime($item['PublishingDate']),
          'FORMFields'     => $item['FORMFields'],
        ))
        ->execute();
    }
  }

  // NB: If this is run for the first time we should do an early exit.
  // No need to look for data to delete when no data exists.
  if ($first_run) {
    // Calling functions should never set this. Only called from hook_install.
    return;
  }

  // Now we handle the known_ids that has not been found in the article-list.
  if (!empty($known_ids)) {
    // We keep the titles-list updated, and because this is used primarily
    // to autocomplete titles on import we MUST keep it up to date, and can
    // not have "non-availlable" article titles "ready for import"!
    $aid_list = implode(',', array_keys($known_ids));
    $sql = "UPDATE {os2web_borger_dk_article_titles} SET `ArticleStatus` = -1 WHERE `ArticleID` IN (:aids)";
    db_query($sql, array(':aids' => $aid_list));

    // We create a queue for handling the many SoapClient->request's needed
    // for examinig if all unknown articles has been deleted.
    $queue = DrupalQueue::get('os2web_borger_dk_check_status_queue');

    $sql = 'SELECT `nid`, `external_id` FROM {os2web_borger_dk_article} WHERE `external_id` IN (:aids)';
    $result = db_query($sql, array(':aids' => $aid_list));

    // Step through the known_ids that has not been found.
    foreach ($result as $item) {
      $qitem = array('nid' => $item->nid, 'external_id' => $item->external_id);
      $queue->createItem($qitem);
      $log .= '=> Item: ' . print_r($qitem, TRUE) . "\n";
    }
  }
}

/**
 * Implements hook_cron_queue_info().
 */
function os2web_borger_dk_cron_queue_info() {
  $queues = array();
  $queues['os2web_borger_dk_delete_queue'] = array(
    // Function to call for each item.
    'worker callback' => '_os2web_borger_dk_delete_queue_callback',
    // Seconds to spend working on the queue.
    'time' => 20,
  );
  $queues['os2web_borger_dk_check_status_queue'] = array(
    // Function to call for each item.
    'worker callback' => '_os2web_borger_dk_status_check_queue_callback',
    // Seconds to spend working on the queue.
    'time' => 60,
  );

  return $queues;
}

/**
 * Function _os2web_borger_dk_status_check_queue_callback().
 */
function _os2web_borger_dk_status_check_queue_callback($data) {
  // Uses SoapClient->request GetArticleByID to check the
  // status of a Borger.dk Article with the Borger.dk-WebService.
  if (!isset($data['nid']) || !isset($data['external_id'])) {
    return;
  }

  $wsdl = variable_get('os2web_borger_dk_webservice', 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl');
  // Try to get this one article, to see if it still exists.
  $item = _os2web_borger_dk_GetArticleByID($data['external_id'], $wsdl);
  if (!empty($item['error']) && $item['error'] == 1) {
    if (!empty($item['error_type']) && ($item['error_type'] == 'not_found')) {
      // Not found articles are marked for deletion,
      // which is handled by another queue.
      $sql = "UPDATE {os2web_borger_dk_article} SET `external_status` = -2 WHERE `nid` = :nid";
      db_query($sql, array(':nid' => $data['nid']));
    }
    else {
      $msg  = 'Borger.dk webservice returned an error for an imported article with id=%aid. ';
      $msg .= 'The error-struck article can be found here: %alink. ';
      $msg .= 'Error code: %ecode. Error string: %estring';
      watchdog(
        'OS2web Borger.dk',
        $msg,
        $variables = array(
          '%aid' => $data['external_id'],
          '%alink' => l(t('node/') . $data['nid']),
          '%ecode' => $item['error_code'],
          '%estring' => $item['error_string'])
      );
    }
  }
  elseif (!isset($item['Exceptions'])) {
    // Well - NO ERRORS AND NO EXCEPTIONS - WHATS UP:
    // We un-mark this title, and let it point back to the borger_dk_article.
    $sql = "UPDATE {os2web_borger_dk_article_titles} SET `ArticleStatus` = :nid WHERE `ArticleID` = :aid";
    db_query($sql, array(':nid' => $data['nid'], ':aid' => $data['external_id']));
  }
}

/**
 * Function _os2web_borger_dk_delete_queue_callback().
 */
function _os2web_borger_dk_delete_queue_callback($data) {
  // This function loads a node with node_load, sets the status
  // to un-published, writes a log-message,
  // and stores it as a new revision.
  // Each data-element point to an article that should be deleted / unpublished.
  // First we load the current node.
  $node = node_load($data['nid']);
  // Then we put our update into a new revision for easy re-publishing.
  $node->revision = 1;
  // And we make it un-published.
  $node->status = 0;
  // We also insert a log-message that explains our actions.
  $node->log = t('Un-publishing article because it has been deleted at Borger.dk. This is an un-published copy of the revision from %date.', array('%date' => format_date($node->revision_timestamp)));
  // And we mark the "external-link-table-item" as deleted (status = -1).
  $node->os2web_borger_dk_article['external_status'] = -1;
  // Finally we store the new revision.
  node_save($node);

  $msg = 'Cronjob has un-published the article node/%nid because is has been deleted at Borger.dk';
  watchdog('OS2web Borger.dk', $msg, $variables = array('%nid' => $node->nid));
}

/**
 * Function _os2web_borger_dk_update_node_content().
 */
function _os2web_borger_dk_update_node_content($nid, $article) {
  if (!empty($article['Exceptions']) || !empty($article['error'])) {
    return;
  }
  // First we load the corresponding node.
  $node = node_load($nid, NULL, TRUE);

  // And we update all the node-fields with the article-values.
  $node->title = $article['title'];

  $body = '';
  foreach ($article['kernetekst'] as $div => $content) {
    $body .= $content . "\n";
  }

  $node->title                                            = (!empty($article['title'])) ? $article['title'] : '';

  $node->body['und'][0]['value']                          = $body;
  $node->body['und'][0]['safe_value']                     = $body;
  $node->body['und'][0]['format']                         = 'full_html';

  $node->field_os2web_borger_dk_byline['und'][0]['value']           = (!empty($article['byline'])) ? $article['byline'] : '';
  $node->field_os2web_borger_dk_byline['und'][0]['safe_value']      = (!empty($article['byline'])) ? $article['byline'] : '';
  $node->field_os2web_borger_dk_byline['und'][0]['format']          = 'plaintext';

  $node->field_os2web_borger_dk_header['und'][0]['value']           = (!empty($article['header'])) ? $article['header'] : '';
  $node->field_os2web_borger_dk_header['und'][0]['safe_value']      = (!empty($article['header'])) ? $article['header'] : '';
  $node->field_os2web_borger_dk_header['und'][0]['format']          = 'full_html';

  $node->field_os2web_borger_dk_selfservi['und'][0]['value']      = (!empty($article['selvbetjeningslinks'])) ? $article['selvbetjeningslinks'] : '';
  $node->field_os2web_borger_dk_selfservi['und'][0]['safe_value'] = (!empty($article['selvbetjeningslinks'])) ? $article['selvbetjeningslinks'] : '';
  $node->field_os2web_borger_dk_selfservi['und'][0]['format']     = 'full_html';

  $node->field_os2web_borger_dk_recommend['und'][0]['value']      = (!empty($article['anbefaler'])) ? $article['anbefaler'] : '';
  $node->field_os2web_borger_dk_recommend['und'][0]['safe_value'] = (!empty($article['anbefaler'])) ? $article['anbefaler'] : '';
  $node->field_os2web_borger_dk_recommend['und'][0]['format']     = 'full_html';

  $node->field_os2web_borger_dk_legislati['und'][0]['value']      = (!empty($article['lovgivning'])) ? $article['lovgivning'] : '';
  $node->field_os2web_borger_dk_legislati['und'][0]['safe_value'] = (!empty($article['lovgivning'])) ? $article['lovgivning'] : '';
  $node->field_os2web_borger_dk_legislati['und'][0]['format']     = 'full_html';

  $node->field_os2web_borger_dk_shortlist['und'][0]['value']        = (!empty($article['huskeliste'])) ? $article['huskeliste'] : '';
  $node->field_os2web_borger_dk_shortlist['und'][0]['safe_value']   = (!empty($article['huskeliste'])) ? $article['huskeliste'] : '';
  $node->field_os2web_borger_dk_shortlist['und'][0]['format']       = 'full_html';

  // Some fields from borger_dk_article can not be syncronized nor changed here.
  $node->os2web_borger_dk_article['external_id']    = $article['external_id'];
  $node->os2web_borger_dk_article['external_url']   = $article['external_url'];
  $node->os2web_borger_dk_article['published_date'] = strtotime($article['published_date']);
  $node->os2web_borger_dk_article['last_updated']   = strtotime($article['last_updated']);

  node_save($node);
  db_update('os2web_borger_dk_article')
    ->fields(array('last_updated' => strtotime($article['last_updated'])))
    ->condition('nid', $nid, '=')
    ->execute();
}

/**
 * Function _os2web_borger_dk_GetAllArticles().
 */
function _os2web_borger_dk_GetAllArticles($wsdl = 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl') {
  // This function uses the Borger.dk Webservice
  // GetAllArticles in order to fetch a list of
  // availlable articles (by title).
  $errors = array();
  // Then we can start using a new soap-client to
  // find the article-ID from the Borger.dk-URL.
  $client = new SoapClient($wsdl, array('exceptions' => 0));
  // First we make sure to keep requests/minute within given limits.
  _os2web_borger_dk_check_webservice_constraints();
  // Then we execute our webservice-request.
  $result_list = $client->GetAllArticles();
  if (is_soap_fault($result_list)) {
    $errors = _os2web_borger_dk_translate_soap_fault('GetAllArticles', $result_list->faultcode, $result_list->faultstring);
    return $errors;
  }

  $article_items = array();
  // Then we get the result-list from the specified webservice.
  $article_list = $result_list->GetAllArticlesResult;
  if (is_soap_fault($article_list)) {
    $errors = _os2web_borger_dk_translate_soap_fault('GetAllArticlesResult', $article_list->faultcode, $article_list->faultstring);

    return $errors;
  }
  else {
    // Now we step through all the fetched articles and convert them to arrays
    // of wanted field-sets.
    // NB!!: The webservice places ONE found article directly in the response.
    // But TWO found articles are placed in an array.
    if (is_array($article_list->ArticleDescription)) {
      foreach ($article_list->ArticleDescription as $id => $article) {
        $new_item = _os2web_borger_dk_parse_borgerdk_article_desc($article);
        $article_items[] = $new_item;
      }
    }
    else {
      foreach ($article_list as $id => $article) {
        $new_item = _os2web_borger_dk_parse_borgerdk_article_desc($article);
        $article_items[] = $new_item;
      }
    }
  }

  return $article_items;
}

/**
 * Function _os2web_borger_dk_GetArticlesByIDs().
 */
function _os2web_borger_dk_GetArticlesByIDs($borgerdk_ids = NULL, $updated_after = NULL, $wsdl = 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl') {
  // This function uses the Borger.dk WebService GetArticlesByIDs
  // in order to fetch a list of Borger.dk-articles by article-IDs
  // and an "updateAfter"-datestamp.
  // We must have an array of items to fetch either specified by a list of
  // articleIDs or specified by an updatedAfter timestamp.
  if (empty($borgerdk_ids) && empty($updated_after)) {
    return array();
  }

  $errors = array();
  // Then we can start using a new soap-client to find
  // the article-ID from the Borger.dk-URL.
  $client = new SoapClient($wsdl, array('exceptions' => 0));
  if (empty($updated_after) && !empty($borgerdk_ids)) {
    // We have a specified list of articles to fetch.
    // First we make sure to keep requests/minute within given limits.
    _os2web_borger_dk_check_webservice_constraints();
    // Then we execute our webservice-request.
    $result_list = $client->GetArticlesByIDs(array('articleIDs' => $borgerdk_ids));
    if (is_soap_fault($result_list)) {
      $errors = _os2web_borger_dk_translate_soap_fault($borgerdk_ids, $result_list->faultcode, $result_list->faultstring);

      return $errors;
    }
  }
  elseif (!empty($updated_after) && empty($borgerdk_ids)) {
    // First we make sure to keep requests/minute within given limits.
    _os2web_borger_dk_check_webservice_constraints();
    // Then we execute our webservice-request.
    // We have a specified date, and want all articles that have been
    // updated since the given date.
    $result_list = $client->GetArticlesByIDs(array('updatedAfter' => $updated_after));
    if (is_soap_fault($result_list)) {
      $errors = _os2web_borger_dk_translate_soap_fault(array('updatedAfter' => $updated_after), $result_list->faultcode, $result_list->faultstring);

      return $errors;
    }
  }
  elseif (!empty($updated_after) && !empty($borgerdk_ids)) {
    // First we make sure to keep requests/minute within given limits.
    _os2web_borger_dk_check_webservice_constraints();
    // Then we execute our webservice-request.
    // We have a specified date, and a specified list of article-IDs. We
    // want all articles from that list that has also been updated since
    // the given date.
    $result_list = $client->GetArticlesByIDs(array('articleIDs' => $borgerdk_ids, 'updatedAfter' => $updated_after));
    if (is_soap_fault($result_list)) {
      $errors = _os2web_borger_dk_translate_soap_fault(array('articleIDs' => $borgerdk_ids, 'updatedAfter' => $updated_after), $result_list->faultcode, $result_list->faultstring);

      return $errors;
    }
  }

  $article_items = array();
  // Then we get the result-list from the specified webservice.
  $article_list = $result_list->GetArticlesByIDsResult;
  if (is_soap_fault($article_list)) {
    $errors = _os2web_borger_dk_translate_soap_fault('GetArticlesByIDsResult', $article_list->faultcode, $article_list->faultstring);

    return $errors;
  }
  else {
    // Now we step through all the fetched articles and convert them to arrays
    // of wanted field-sets.
    $found_ids = array();
    // NB!!: The webservice places ONE found article directly in the response.
    // But TWO found articles are placed in an array.
    if (is_array($article_list->Article)) {
      foreach ($article_list->Article as $id => $article) {
        $new_item = _os2web_borger_dk_parse_borgerdk_article($article);
        $found_ids[$new_item['external_id']] = 1;
        $article_items[] = $new_item;
      }
    }
    else {
      foreach ($article_list as $id => $article) {
        $new_item = _os2web_borger_dk_parse_borgerdk_article($article);
        $found_ids[$new_item['external_id']] = 1;
        $article_items[] = $new_item;
      }
    }
    // Now we check if all the wanted articles was found.
    if (!empty($borgerdk_ids)) {
      foreach ($borgerdk_ids as $id) {
        if (empty($found_ids[$id])) {
          $article_items[] = array(
            'external_id' => $id,
            'no_updates'  => 1,
          );
        }
      }
    }
  }

  return $article_items;
}

/**
 * Function _os2web_borger_dk_GetArticleByUrl().
 */
function _os2web_borger_dk_GetArticleByUrl($borgerdk_url, $wsdl = 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl') {
  // This function uses the Borger.dk WebServices
  // GetArticleIDByUrl and GetArticleByID in order
  // to fetch a Borger.dk-article by its URL.
  $error = array();
  // The URL of the Borger.dk-article to get must
  // be given as argument.
  if (empty($borgerdk_url)) {
    return $error;
  }

  // We start by using a soap-client to find the article-ID
  // from the Borger.dk-URL.
  $client = new SoapClient($wsdl, array('exceptions' => 0));
  // First we make sure to keep requests/minute within given limits.
  _os2web_borger_dk_check_webservice_constraints();
  // Then we execute our webservice-request.
  $result_id = $client->GetArticleIDByUrl(array('url' => $borgerdk_url));

  if (is_soap_fault($result_id)) {
    // An error was encountered and we examine it more closely.
    $error = _os2web_borger_dk_translate_soap_fault($borgerdk_url, $result_id->faultcode, $result_id->faultstring);

    return $error;
  }
  else {
    // If no errors was encountered we fetch the resulting ArticleID.
    $id2get = $result_id->GetArticleIDByUrlResult->ArticleID;

    // Then we use the article-ID to fetch the actual Borger.dk-article.
    $article = _os2web_borger_dk_GetArticleByID($id2get);
  }

  return $article;
}

/**
 * Function _os2web_borger_dk_GetArticleByID().
 */
function _os2web_borger_dk_GetArticleByID($borgerdk_id, $wsdl = 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl') {
  // Check the admin setting.
  $admin_municipality = variable_get('os2web_borger_dk_municipality_active');
  // This function uses the Borger.dk WebService
  // GetArticleByID in order to fetch a Borger.dk-article
  // by its article-ID.
  $error = array();
  // The ID of the Borger.dk-article to get must be given as argument.
  if (empty($borgerdk_id)) {
    return $error;
  }

  // We use a soap-client to fetch the specified article from Borger.dk.
  $client = new SoapClient($wsdl, array('exceptions' => 0));
  // First we make sure to keep requests/minute within given limits.
  _os2web_borger_dk_check_webservice_constraints();
  // Then we execute our webservice-request.
  $array_get_article = array('articleID' => $borgerdk_id);
  // If municipality is set, then get article by id and municipality code.
  if ($admin_municipality != 0)  {
    $array_get_article['municipalityCode'] = $admin_municipality;
  }
  $result_article = $client->GetArticleByID($array_get_article);
  if (is_soap_fault($result_article)) {
    // An error was encountered and we examine it more closely.
    $error = _os2web_borger_dk_translate_soap_fault($borgerdk_id, $result_article->faultcode, $result_article->faultstring);

    return $error;
  }
  else {
    $article = $result_article->GetArticleByIDResult;
    if (is_soap_fault($article)) {
      // An error was encountered and we examine it more closely.
      $error = _os2web_borger_dk_translate_soap_fault($borgerdk_id, $article->faultcode, $article->faultstring);
      return $error;
    }
  }

  return _os2web_borger_dk_parse_borgerdk_article($article);
}

/**
 * Function _os2web_borger_dk_GetAllSites
 * This function uses the Borger.dk Webservice GetAllSites
 * in order to fetch the menu-structure from Borger.dk
 */
function _os2web_borger_dk_GetAllSites($wsdl = 'https://www.borger.dk/_vti_bin/borger/ArticleExport.svc?wsdl') {
  $errors = array();
  $menu_items = array();

  // Then we can start using a new soap-client to find the article-ID from the Borger.dk-URL
  $client = new SoapClient($wsdl, array('exceptions' => 0));
  // First we make sure to keep requests/minute within given limits.
  _os2web_borger_dk_check_webservice_constraints();
  // Then we execute our webservice-request.
  $result_list = $client->GetAllSites();
  if (is_soap_fault($result_list)) {
    $errors = _os2web_borger_dk_articles_translate_soap_fault('GetAllSites', $result_list->faultcode, $result_list->faultstring);

    return $errors;
  }

  $menu_items = array();
  // Then we get the result-list from the specified webservice
  $menu_list = $result_list->GetAllSitesResult;
  if (is_soap_fault($menu_list)) {
    $errors = _os2web_borger_dk_articles_translate_soap_fault('GetAllSitesResult', $menu_list->faultcode, $menu_list->faultstring);

    return $errors;
  }
  else {
    //print 'GetAllSites found these availlable menu-items at Borger.dk: '. print_r($menu_list, TRUE) ."\n\n";
    // Now we step through all the fetched menu-items and convert them to
    // arrays of wanted field-sets.
    if (is_array($menu_list->Site)) {
      foreach ($menu_list->Site as $id => $menu_item) {
        $new_item = _os2web_borger_dk_parse_borgerdk_menu_item($menu_item);
        $menu_items[] = $new_item;
      }
    }
    else {
      $new_item = _os2web_borger_dk_parse_borgerdk_menu_item($menu_list->Site);
      $menu_items[] = $new_item;
    }
  }

  return $menu_items;
}

/**
 * Function _os2web_borger_dk_build_borger_dk_menustructure().
 */
function _os2web_borger_dk_build_borger_dk_menustructure(&$menu, $new_item) {
  // The very first (/top level) menu item does not have a ParentID.
  $pid = $new_item['ParentID'];
  $sid = $new_item['SiteID'];
  if (empty($new_item['ParentID'])) {
    $menu[$sid] = array();
    $menu[$sid] = $new_item;
    $menu[$sid]['ParentID'] = $sid;
    $menu[$sid]['children'] = array();
    return TRUE;
  }
  else {
    // Check if the parent is already defined.
    if (isset($menu[$pid])) {
      // The parent is defined and we must add this item.
      if (isset($menu[$pid]['children'])) {
        $menu[$pid]['children'][$sid] = $new_item;
      }
      else {
        $menu[$pid]['children'] = array();
        $menu[$pid]['children'][$sid] = $new_item;
      }
      return TRUE;
    }
    else {
      // This must be on a sub-level, and we look for it there.
      foreach ($menu as $id => $sub_level) {
        // We only look at sub_levels with numeric keys
        if (!is_numeric($id) && ($id != 'children')) {
          continue;
        }
        // Check if the ParentID-key is defined at this level
        if (isset($sub_level[$pid])) {
          if (isset($sub_level[$pid]['children'])) {
            $menu[$id][$pid]['children'][$sid] = $new_item;
          }
          else {
            $menu[$id][$pid]['children'] = array();
            $menu[$id][$pid]['children'][$sid] = $new_item;
          }
          return TRUE;
        }
        else {
          if (isset($sub_level['children']) && is_array($sub_level['children'])) {
            // Thewn we look for the item at the next sub-level.
            $result = _os2web_borger_dk_build_borger_dk_menustructure($sub_level['children'], $new_item);
            if ($result) {
              // If a result was found we store the new sub_level in the menu
              $menu[$id] = $sub_level;
              return TRUE;
            }
          }
        }
      }
    }
  }

  return FALSE;
}

function _os2web_borger_dk_form_tag_borger_dk_articles($vid, $titles_availlable = array(), $update_items = array(), $other_tid = FALSE) {
  foreach ($titles_availlable as $id => $item) {
    // First we check if this is an imported article or not.
    $aid = (isset($item['ArticleID'])) ? $item['ArticleID'] : FALSE;
    // We only tag imported articles.
    if ($aid && isset($update_items[$aid])) {
      $form_fields = unserialize($item['FORMFields']);
      if (!empty($form_fields['FormTasks'])) {
        $node = node_load($update_items[$aid]);
        $save_node = FALSE;
        foreach ($form_fields['FormTasks'] as $id => $task) {
          $task_name = $task['FormTaskName'];
          $task_id   = $task['FormTaskNumber'];
          $term = _os2web_borger_dk_check_form_taxonomy_item($task_id, $task_name, $vid);
          if ($term) {
            $tid = $term->tid;
            $node->field_os2web_borger_dk_formterm['und'][$tid] = (array) $term;
            $save_node = TRUE;
          }
        }
        // We only save/update the node if any terms were attached.
        if ($save_node) {
          node_save($node);
        }
        else {
          // None of the taxonomy-terms given were found among the
          // FORM-taxonomies. So we must tag this article with the
          // "Other"-tag.
          if ($other_tid) {
            $term = taxonomy_term_load($other_tid);
            $node->field_os2web_borger_dk_formterm['und'][$other_tid] = (array) $term;
            node_save($node);
          }
          else {
            $path = 'node/'. $node->nid;
            $msg = 'Could not tag the article with nid=%nid (link: %url), with the "Other"-tag. No such tag exists.';
            watchdog('Borger.dk-articles', $msg, $variables = array('%nid' => $node->nid, '%url' => l($path, $path)));
          }
        }
      }
    }
  }
}

/**
 * This function parses a Borger.dk-MenuItemDescription and extracts all
 * the field values we want for our Borger.dk-menu-structure.
 */
function _os2web_borger_dk_parse_borgerdk_menu_item($menu_item) {
  // First we extract the directly accessible fields from the ArticleDescription
  //ENT_NOQUOTES
  $pid = (isset($menu_item->ParentID)) ? $menu_item->ParentID : '';
  $borgerdk_menu = array(
    'ParentID'  => $pid,
    'SiteID'    => $menu_item->SiteID,
    'SiteName'  => html_entity_decode($menu_item->SiteName, ENT_NOQUOTES, 'UTF-8'),
    'SiteTitle' => $menu_item->SiteTitle,
  );

  return $borgerdk_menu;
}

/**
 * Function _os2web_borger_dk_parse_borgerdk_article().
 */
function _os2web_borger_dk_parse_borgerdk_article($article) {
  // This function can parse a Borger.dk XML-article and extract
  // all the field values we want for our Drupal-nodes.
  $borgerdk_article = array(
    'title'          => html_entity_decode($article->ArticleTitle, ENT_NOQUOTES, 'UTF-8'),
    'header'         => html_entity_decode($article->ArticleHeader, ENT_NOQUOTES, 'UTF-8'),
    'external_id'    => $article->ArticleID,
    'external_url'   => $article->ArticleUrl,
    'last_updated'   => $article->LastUpdated,
    'published_date' => $article->PublishingDate,
  );

  // We need to parse (using simpleXML) the content in order to f
  // ind embedded field-values:
  // Based on example from:
  // http://stackoverflow.com/questions/66358
  // 49/can-simplexml-be-used-to-rifle-through-html
  $doc = new DOMDocument('1.0', 'UTF-8');
  $doc->strictErrorChecking = FALSE;
  $doc->loadHTML('<?xml encoding="UTF-8">' . $article->Content);
  $xml = simplexml_import_dom($doc);

  foreach ($xml->body->div as $div) {
    $div_id = $div->attributes()->id;
    switch ($div_id) {
      case 'selvbetjeningslinks':
        $borgerdk_article['selvbetjeningslinks'] = _os2web_borger_dk_create_general_html($div);
        break;

      case 'kernetekst':
        $borgerdk_article['kernetekst']          = _os2web_borger_dk_create_kernetekst_html($div);
        break;

      case 'byline':
        $byline                                  = _os2web_borger_dk_create_general_html($div->div);
        if (FALSE !== strpos($byline, '<div>Skrevet af')) {
          $byline = trim($byline);
          $new_byline = preg_replace("/<div>(Skrevet af .+?)<\/div>/i", "$1", $byline, 1);
          if (0 < strlen($new_byline)) {
            // We only overwrite the byline if we found some replacement text.
            $byline = $new_byline;
          }
        }
        $borgerdk_article['byline'] = $byline;
        break;

      case 'anbefaler':
        $borgerdk_article['anbefaler']           = _os2web_borger_dk_create_general_html($div);
        break;

      case 'huskeliste':
        $borgerdk_article['huskeliste']          = _os2web_borger_dk_create_general_html($div);
        break;

      case 'lovgivning':
        $borgerdk_article['lovgivning']          = _os2web_borger_dk_create_general_html($div);
        break;
    }
  }

  // Finally we check if the article contained embedded errors.
  $dom_html = $doc->saveHTML();
  if (strpos($dom_html, 'Exception has been thrown by the target of an invocation')) {
    $borgerdk_article['Exceptions'] = 1;
  }
  return $borgerdk_article;
}

/**
 * Function _os2web_borger_dk_parse_borgerdk_article_desc().
 */
function _os2web_borger_dk_parse_borgerdk_article_desc($article) {
  // This function parses a Borger.dk-ArticleDescription and
  // extracts all the field values we want for our list of
  // titles (for autocompletion etc).
  // First we extract the directly accessible fields from the
  // ArticleDescription.
  $borgerdk_title = array(
    'ArticleID'      => $article->ArticleID,
    'ArticleTitle'   => html_entity_decode($article->ArticleTitle, ENT_NOQUOTES, 'UTF-8'),
    'ArticleUrl'     => $article->ArticleUrl,
    'LastUpdated'    => $article->LastUpdated,
    'PublishingDate' => $article->PublishingDate,
  );

  // Then we find all FORM-elements and create a new serialized array.
  $form_elements = array(
    'FormServiceAreas' => (isset($article->FormServiceAreas)) ? $article->FormServiceAreas : NULL,
    'FormTaskAreas'    => (isset($article->FormTaskAreas)) ? $article->FormTaskAreas : NULL,
  );

  $form_tasks = array();
  $article_formtasks = $article->FormTasks;
  if ((isset($article_formtasks->FormTask)) && is_array($article_formtasks->FormTask)) {
    foreach ($article_formtasks->FormTask as $id => $formtask) {
      $task = array(
        'FormTaskName'   => $formtask->FormTaskName,
        'FormTaskNumber' => $formtask->FormTaskNumber,
      );
      $form_tasks[] = $task;
    }
  }
  else {
    if (isset($article_formtasks->FormTask)) {
      $single_task = $article_formtasks->FormTask;
      $task = array(
        'FormTaskName'   => $single_task->FormTaskName,
        'FormTaskNumber' => $single_task->FormTaskNumber,
      );
      $form_tasks[] = $task;
    }
  }
  // Then we add the found FORM-elements to the return array.
  $form_elements['FormTasks'] = $form_tasks;
  $borgerdk_title['FORMFields'] = serialize($form_elements);

  return $borgerdk_title;
}

/**
 * Function _os2web_borger_dk_create_kernetekst_html().
 */
function _os2web_borger_dk_create_kernetekst_html($xml) {
  // This function steps through the so called microArticle's
  // and converts plus concatenates each element as HTML.
  $output = array();
  $counter = 1;
  $baseclass = 'mArticle';
  foreach ($xml->div as $element) {
    $div_attr = $element->attributes()->id;
    $search = '<div id="' . $div_attr  . '">';
    $replace = '<div class="microArticle" id="' . $div_attr  . '">';
    $html = _os2web_borger_dk_create_html_from_xml($element, $search, $replace);

    // We replace the first <h2>-tag with <h2 class="mArticleX">.
    $pattern = '/<h2>/';
    $replacement = '<h2 class="mArticle" id="' . $baseclass . $counter . '">';
    $html = preg_replace($pattern, $replacement, $html, 1);

    // And we replace the first <div>-tag with <div class="mArticleX">.
    $pattern = '/<div>/';
    $replacement = '<div class="' . $baseclass . $counter . ' mArticle">';
    $html = preg_replace($pattern, $replacement, $html, 1);

    $output["$div_attr"] = $html;

    // Then we update the counter for the next kernetekst-div.
    $counter += 1;
  }

  return $output;
}

/**
 * This function converts a list of XML elements to HTML.
 */
function _os2web_borger_dk_create_general_html($xml) {
  $output = '';

  // We convert each of the XML elements to HTML.
  foreach ($xml as $element) {
    // We use a general method to convert XML to HTML.
    $output .= _os2web_borger_dk_create_html_from_xml($element);
    $output .= "\n";
  }

  return $output;
}

/**
 * This function converts XML-entities to ordinary HTML.
 */
function _os2web_borger_dk_create_html_from_xml($xml, $search = NULL, $replace = NULL) {
  // DOMDocuments converts special characters to HTML-characters, and we
  // need to replace some of those back into danish letters. Also <br/>-tags
  // gets replaced with <br>-tags, and we need to convert those as well.
  $substitute = array(
    '<br>' => '<br />',
    '&aelig;' => '%C3%A6',
    '&Aelig;' => '%C3%86',
    '&AElig;' => '%C3%86',
    '&oslash;' => '%C3%B8',
    '&Oslash;' => '%C3%98',
    '&aring;'  => '%C3%A5',
    '&Aring;'  => '%C3%85',
  );
  // If the function is called with a special replacement-string we add
  // the search- and replace-strings to the default substitution array.
  if (!empty($search) && !empty($replace)) {
    $substitute[$search] = $replace;
  }

  // Then we convert the XML to HTML, and substitute special characters.
  $dom = new DOMDocument('1.0', 'UTF-8');
  $dom->loadXML($xml->asXML());
  $dom_html = $dom->saveHTML();
  $dom_html = strtr($dom_html, $substitute);
  $dom_html = urldecode($dom_html);

  return $dom_html;
}

/**
 * Function _os2web_borger_dk_translate_soap_fault().
 */
function _os2web_borger_dk_translate_soap_fault($borgerdk_id, $faultcode, $faultstring) {
  // This function is used to translate SoapClient-errors
  // from string-elements to an array of
  // "real"/"usable" error-information.
  $error = array(
    'error'        => 1,
    'external_id'  => $borgerdk_id,
    'error_code'   => $faultcode,
    'error_string' => $faultstring,
  );

  // We set up an array of known SoapClient errors
  // array of: 'error_type' => '/regex-pattern to use/'.
  $known_errors = array(
    'not_found' => '/^No articles found with ids \'(\d*)\'/',
  );

  // Now we examine the faultstring more closely.
  if ($faultcode == "s:Client") {
    // Then we might know something about that error-type.
    foreach ($known_errors as $error_type => $error_text) {
      $matches = array();
      if (1 == preg_match($error_text, $faultstring, $matches)) {
        // We found a known error type.
        $error['error_type'] = $error_type;

        // Now lets see if there are known matches / digits to return.
        switch ($error_type) {
          case 'not_found':
            $error['not_found_id'] = $matches[1];
            break;

          default:
            break;
        }

        // Finally we break out of the loop for finding this error.
        break;
      }
    }
  }

  return $error;
}

/**
 * Function _os2web_borger_dk_check_webservice_constraints().
 */
function _os2web_borger_dk_check_webservice_constraints() {
  // We start of by getting the webservice request-limits.
  $webservice_request_limit = variable_get('os2web_borger_dk_webservice_request_limit', 100);
  $webservice_time_limit = variable_get('os2web_borger_dk_webservice_time_limit', 60);
  // And we keep track of the number of webservice-requests per timeperiod.
  $os2web_borger_dk_article_count_no = variable_get('os2web_borger_dk_webservice_request_counter', 0);
  $os2web_borger_dk_article_start_time = variable_get('os2web_borger_dk_webservice_time_counter', 1970);
  // We restart the counters if the timer is too old.
  if ($os2web_borger_dk_article_start_time < (time() - $webservice_time_limit)) {
    $os2web_borger_dk_article_count_no = 0;
    $os2web_borger_dk_article_start_time = time();
    variable_set('os2web_borger_dk_webservice_request_counter', 0);
    variable_set('os2web_borger_dk_webservice_time_counter', time());
  }

  // Then we check if the limits has been reached, and it's time for a break.
  if (($webservice_time_limit >= (time() - $os2web_borger_dk_article_start_time)) ||
      ($webservice_request_limit >= $os2web_borger_dk_article_count_no)) {
    // We have reached the work-load limit of 100 items per minute, and must
    // take a small break or the webservice will stop answering us.
    sleep($webservice_time_limit - (time() - $os2web_borger_dk_article_start_time));

    // Then we reset/store the counters for limiting the webservice work-load.
    $os2web_borger_dk_article_count_no = 0;
    $os2web_borger_dk_article_start_time = time();
    variable_set('os2web_borger_dk_webservice_time_counter', time());
  }

  // TODO: Test this function by:
  // 1) Increase counter by 10 instead of by 1.
  // 2) Reduce request_limit to 20 instead of 100.
  // 3) Import 3 articles within time-limit (and perhaps increase time-limit).
  // Update the work-load item counter.
  $os2web_borger_dk_article_count_no += 1;
  variable_set('os2web_borger_dk_webservice_request_counter', $os2web_borger_dk_article_count_no);
}
